### ISSUE TITLE
Questions on the Distributed Trace extension

### ISSUE THREAD

**Issue by ntextreme3** [cloudevents/spec#1021]
## 1. Why not just use `traceparent` as the attribute? 

There is already precedence for doing this with `content-type` in the broader spec. Ex, from [datacontenttype](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#datacontenttype): 

> For some binary mode protocol bindings, this field is directly mapped to the respective protocol's content-type metadata property.

Which is specified in the [HTTP binding spec](https://github.com/cloudevents/spec/blob/main/cloudevents/bindings/http-protocol-binding.md#311-http-content-type)

> For the binary mode, the HTTP Content-Type header value corresponds to (MUST be populated from or written to) the CloudEvents datacontenttype attribute. Note that a ce-datacontenttype HTTP header MUST NOT also be present in the message.

It doesn't feel intuitive to allow both `traceparent` and `ce-traceparent` as distinct things. Which kinda leads to my next questions:

##  2. The spec says ...

> Given a multi hop event transmission, the Distributed Tracing Extension, if used, MUST carry the trace information of the starting trace of the transmission. In other words, it MUST NOT carry trace information of each individual hop, since this information is usually carried using protocol specific headers, understood by tools like OpenTelemetry.

2.1) What's the purpose in changing the behavior of `traceparent` here vs how the W3C spec says it should be? And why not rename it like "starting traceparent" or something if that's the case? 

2.2) Even if there is a good reason, the example seems to allow ignoring the original trace info (by the fact that there are two different traceIDs). Even if you were going to stick with saying traceparent `MUST carry the trace information of the starting trace` -- I feel like other trace info should at least be on the same tree. 

Ex, [current example](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/extensions/distributed-tracing.md) (different trace-id, different parent-id):

> -H 'ce-traceparent:  00-0af7651916cd43dd8448eb211c80319c-b9c7c989f97918e1-01' \
> -H 'traceparent:  00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01' \

In this case, I'd expect something like (same trace-id, different parent-id):

> -H 'ce-traceparent:  00-0af7651916cd43dd8448eb211c80319c-b9c7c989f97918e1-01' \
> -H 'traceparent:  00-0af7651916cd43dd8448eb211c80319c-00f067aa0ba902b7-01' \

**Comment by duglin** [comment]
@joaopgrassi @clemensv any comments?

**Comment by joaopgrassi** [comment]
>2.1) What's the purpose in changing the behavior of traceparent here vs how the W3C spec says it should be? And why not rename it like "starting traceparent" or something if that's the case?

The goal of having the extra `ce-traceparent` is to achieve an "application-only" trace, meaning a trace that does not contain (or is agnostic of) things like protocol-level instrumentation (brokers/intermediaries). 

Imagine this use case: An application is instrumented and sends an event to an intermediary. The intermediary then forwards this event to a consumer. 

The standard `traceparent` propagation is not enough to cover this scenario. If the intermediary is not instrumented, you end up with a broken trace. You can't know who received the initial event and nothing that happened after it. 
Another example: The intermediary _is_ instrumented, but it puts the event into a queue, which is delivered to n consumers after a while. Here you also end up with a broken trace, because after "persisting" the event, the initial trace is done and producer and consumer(s) can't be linked. 

The idea then is when an event is created, a "creation context" (span) is created and attached to the event using the distributed tracing extension (`ce-traceparent`). This creation context is immutable and travels together with the event. Each point it arrives, consumers then add it as a [link](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#specifying-links) on their side, ultimately continuing the initial trace. 

So: `traceparent` changes during each hop, and would be used to trace the "protocol-level" side of things. `ce-traceparent` never changes and it is carried on across each hop, enabling parties to link to this initial creation fact.

>2.2) Even if there is a good reason, the example seems to allow ignoring the original trace info (by the fact that there are two different traceIDs). Even if you were going to stick with saying traceparent MUST carry the trace information of the starting trace -- I feel like other trace info should at least be on the same tree.

This highly depends on the order which things happens and how the CloudEvents SDK work. Your example (same traceid, different span ids) make sense if the order of what I described above is:

1. Event is created in func `myFunc`
2. Span is created and its context is attached to the event, using the extension, becoming the `ce-traceparent`
3. Event is passed to an instrumented HTTP client and is sent
4. `myFunc` exits

This way you will get the create context as the parent, and the HTTP one as a child. Same trace-id, different span ids
>-H 'ce-traceparent: 00-0af7651916cd43dd8448eb211c80319c-b9c7c989f97918e1-01'
-H 'traceparent: 00-0af7651916cd43dd8448eb211c80319c-00f067aa0ba902b7-01' \

But if the `myFunc` exits and the event is sent later on in the code, then the initial "create context" is already finished and the HTTP one is not a child of it anymore:

1. Event is created in func `myFunc`
2. Span is created and its context is attached to the event, using the extension, becoming the `ce-traceparent`
3. `myFunc` exits and returns the event
4. Event is passed to an instrumented HTTP client and is sent

This way you will end up with:

> -H 'ce-traceparent: 00-0af7651916cd43dd8448eb211c80319c-b9c7c989f97918e1-01'
-H 'traceparent: 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01' \

The CloudEvents spec around this was used as a base for the semantic conventions around CloudEvents in OpenTelemetry. It explains the problem and solution in more details, with examples and diagrams. You can check it out here https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/cloudevents.md

It is still experimental and it overlaps in a lot of aspects with instrumentation around messaging systems, which is what the group is working on at the moment. The `ce-traceparent` additional context is also a concept that will be used in messaging systems, since they face the same issues (producers-intermediaries-consumer(s)). There's even drafts for how it should look like in different protocols [AMQP](https://w3c.github.io/trace-context-amqp/), [MQTT](https://w3c.github.io/trace-context-mqtt/)

**Comment by ntextreme3** [comment]
Thanks for the examples!

> The CloudEvents spec around this was used as a base for the semantic conventions around CloudEvents in OpenTelemetry. It explains the problem and solution in more details, with examples and diagrams. You can check it out here https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/cloudevents.md

So in the semantic conventions for CloudEvents, it looks like the suggestion is to relate the Consumer back to the Producer via a "Link". Is there a reason that that would be preferred over just having 1 traceparent root?

Ex: 

1. App1 sends a CloudEvent with `ce-traceparent` following the same rules as `traceparent` to an intermediary
2. Intermediary puts the CloudEvent on some Queue
3. App2 pulls from the Queue and sees `ce-traceparent`, extracts the context, and uses it the same way it would use an incoming `traceparent`. 
4. If App2 calls out to something else or puts a new CloudEvent on a queue somewhere, it injects `ce-traceparent` (not the original one), the same way the instrumentation libraries would inject `traceparent`. The CloudEvent is just a carrier. 

You lose the intermediary spans, but they were not instrumented so you'd lose them anyway. Then App1 and App2 would be on the same "tree", rather than associated via a Link (granted, trees can get pretty big this way). 

So if you have a non-CloudEvent output (like an instrumented HTTP call to something), inject the then current context to traceparent headers, and if you have a CloudEvent output, inject the then current context to CloudEvent. 

I think I'm missing the benefit of them being on different trace-ids. I see how ce-traceparent helps carry the tracecontext through non-instrumented applications and queues, etc. But why make the behavior of the fields different?

**Comment by joaopgrassi** [comment]
>Thanks for the examples!

Sure! Sorry for the wall of text, but it's a topic that is tricky to answer in a few words 😅

> App2 pulls from the Queue and sees ce-traceparent, extracts the context, and uses it the same way it would use an incoming traceparent.

Yes, you are right this _would_ work. But it's not ideal for a couple of reasons:

- You lose whatever current context you have at that moment. Imagine the poll operation happened during some user request. If you take the context from the event and use that instead to continue the trace, you will lose all the information about the initial user request. It will be another broken trace in your system. With links you can keep both worlds - the consumer trace contains everything that triggered the poll operation + you are able to know where it came from and why. 

- You require users to manipulate and deal with context propagation "manually". This can open up to problems as basically everyone can do whatever they want. Sure, they can still do it in the end, but as a specification we are trying to reach a common standard that works well for everyone, without having them to know/manage all these inner details. Ultimately all this linking/extracting is hidden away and done by the libraries itself.

Links are also the only way to solve cases where a consumer receives a batch of events. I'm not sure if it's the case with the existing CloudEvents SDKs, but it is certainly a case for messaging systems. Since a given trace can only have one parent, when a consumer receives a batch of messages/events, the only way to connect producer/consumer is via links. Since there's a lot of overlap between the nature of CloudEvents and messaging systems, we are trying to keep both specifications/recommendations as close as possible.

**Comment by ntextreme3** [comment]
I think that makes sense, ok then so:

> Given a multi hop event transmission, the Distributed Tracing Extension, if used, MUST carry the trace information of the starting trace of the transmission.

The "multi hop" period described there refers to the event passing through something like a queue, and _not_ saying that `ce-traceparent` should always be carried forward **forever** matching the initial app?

Ex: 

1. App1 -> Intermediary1 -> Queue1 -> App2
2. App2 gets Linked to App1
3. App2 does some work with the Event and sends its `ce-traceparent` value in a new Event -> Intermediary -> Queue -> App3
4. **App3 would create a link to App2 (instead of App1), correct?** 

The way I read it here at first is that App3...AppN would always receive `ce-traceparent` matching the "starting trace" (App1). So in other words, the "multi hop" period ends once the next instrumented app consumes the message, and the "starting" `ce-traceparent` doesn't continue propagating forever?

**Comment by joaopgrassi** [comment]
> The way I read it here at first is that App3...AppN would always receive ce-traceparent matching the "starting trace" (App1). 

If **the same** initial event is forwarded (or travels) to/from AppN, then all of those will link to App1. The simple way to think is: subsequent apps will extract whatever context is in the event and add it as a link to its own trace. If the initial event "goes through many hops" it's then clear all of those hops will link to the initial `App1`.

> the "multi hop" period ends once the next instrumented app consumes the message, and the "starting" ce-traceparent doesn't continue propagating forever?

Yes, exactly. The multi hop ends when the next consumer doesn't forward the event anymore. It "settles" it.

In your example, when `App2` receives the initial event from `App1`, it will start its own trace, and extract the context (`ce-traceparent`) from the event and add it as a link, linking `App2` <> `App1`. Then say, the event in `App2` caused some side effect and `App2` needs to send a new event to `App3`. Then the whole process starts again - `App2` creates the new event, a new span and adds it inside of it. The new event is forwarded and, at some point, `App3` receives it. Then you have a link of `App3` <> `App2`. 

I did some drawings for the case above, maybe it helps

Apps interaction:
![image](https://user-images.githubusercontent.com/5938087/173035892-57032b9d-2e49-44ef-b677-ff28c9c8bd68.png)

Achieved trace, using the conventions from here/OpenTelemetry
![image](https://user-images.githubusercontent.com/5938087/173037198-e96dcc2a-ca54-4bbc-9598-967fafc9b7da.png)

Of course, all other actions that happens in either apps will be part of each trace, as long there's some auto-instrumentation in place. Say, `App2` makes some Db calls and those are instrumented. It will all be part of `App2`'s trace.

**Comment by ntextreme3** [comment]
I'm all good here then, thanks!
