### ISSUE TITLE
Question on carrying custom metadata between systems

### ISSUE THREAD

**Issue by ntextreme3** [cloudevents/spec#1022]
Looking at a spec like, for example, HTTP or Kafka, which both support a concept of Headers -- are there any provisions that apply generically for custom metadata? Or do we consider anything "custom" really an "extension" and should be well defined? 

Example: Say you have an application that is ignorant of CloudEvents and it produces messages to a Kafka topic with custom metadata set in Kafka headers. Now you want to consume a record from that topic, convert it to a CloudEvent, and sent it via HTTP to another system (including the custom metadata). 

How do you get this metadata from Kafka Headers to the HTTP system? Is anything like that covered by any of the specs here? Or is this just not supported, and the original producer should adhere to CloudEvents specs, define an extension, and set the metadata as "extension attributes"?

**Comment by duglin** [comment]
If you want to convert a custom Kafka header (ignoring well defined ones) into a CE extension attribute then it shouldn't be any harder than to just add the `ce-` prefix to it and make sure the name adheres to the CE [rules](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#naming-conventions). Does that help?

**Comment by Woile** [comment]
Hey @duglin could you expand on:

> ignoring well defined ones

Does it mean CE defines kafka headers? I couldn't find a link to this.
Thanks

**Comment by duglin** [comment]
I just meant that you wouldn't want to convert headers like `content-type` to `ce-content-type`, so Kafka well-known headers.

Yes, 3.2 is for "CE binary mode" and 3.3 shows "CE structured mode". Which you use depends on whether you want your event wrapped with CE metadata (structured) in the body or whether you want your event untouched/unwrapped and then the CE metadata appears as headers (binary).

**Comment by pierDipi** [comment]
I guess what you're looking for is a well-defined <protocol / system> event to CloudEvent transformation (<protocol / system > being HTTP or Kafka in your case), the spec defines "adapters" for some systems https://github.com/cloudevents/spec/tree/main/cloudevents/adapters but there isn't one for Kafka (or a generic one for "system that supports headers"), so everyone is defining its own protocol/rules (an open-source example that I'm aware of is Knative, it defines its own mapping to go from generic Kafka record to CloudEvent representation of that record but it's a Knative thing).

note: I don't think that CloudEvents bindings (like https://github.com/cloudevents/spec/blob/main/cloudevents/bindings/kafka-protocol-binding.md) are relevant to your questions because they define how a CloudEvent maps to a protocol but in this case, we don't have a proper CloudEvent.

> If you want to convert a custom Kafka header (ignoring well defined ones) into a CE extension attribute then it shouldn't be any harder than to just add the `ce-` prefix to it and make sure the name adheres to the CE [rules](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#naming-conventions). Does that help?

This is kinda defining an adapter for Kafka records.

I totally see the value of having more adapters in the spec for additional systems to increase interoperability.

**Comment by ntextreme3** [comment]
> > If you want to convert a custom Kafka header (ignoring well defined ones) into a CE extension attribute then it shouldn't be any harder than to just add the `ce-` prefix to it and make sure the name adheres to the CE [rules](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#naming-conventions). Does that help?
> 
> This is kinda defining an adapter for Kafka records but it isn't spec-defined.

👍 Yeah I think this is exactly what I'm looking for. Headers was one example, another would be well defined rules for things like "id" and "source" where the spec just says that 'the combination must be unique'. 

Since you mentioned Knative, I took a look at their KafkaSource and they have things like [this](https://learning.oreilly.com/library/view/knative-cookbook/9781492061182/ch04.html#:-:text=ce-id%3Dpartition,source%23my-topic) (where they define "id" as partition+offset and source as some path to a `topic`) and [this](https://knative.dev/docs/eventing/sources/kafka-source/#optional-specify-the-key-deserializer) (where they say they put kafka headers in an "extension starting with `kafkaheader`"). Those were the kinds of rules I was looking for here (instead of making up my own).

**Comment by duglin** [comment]
@ntextreme3 where are we on this one? If you think a "kafka adapter" would be useful, would you be interested in taking a first stab at it?

**Comment by duglin** [comment]
Any objection to closing this one?

**Comment by ntextreme3** [comment]
Yeah that's fine. I do think having an official adapter will be useful. If I have time I might come back to it.

**Comment by duglin** [comment]
that would be great - thanks!
