### ISSUE TITLE
CloudEvents additional custom data

### ISSUE THREAD

**Issue by xibz** [cloudevents/spec#1024]
So, I am talking with [cdEvents](https://github.com/cdevents/spec) who use cloudevents as the underlying transport format, and one thing I noticed is that they have an additional field called `payload` in their requests.

```json
{
    "specversion" : "1.0",
    "type" : "com.github.pull_request.opened",
    "source" : "https://github.com/cloudevents/spec/pull",
    "subject" : "123",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "datacontenttype" : "text/xml",
    "data" : "<much wow=\"xml\"/>" // Notice the nesting of the data
}
```

This unfortunately is a breaking change to anyone adhering to this standard, so instead I proposed some alternative solution in [cdEvents#40](https://github.com/cdevents/spec/issues/40). The basic idea is making data a top level parent, and introducing something like a `cd-events-metadata` field in the payload. So instead

```
<much_wow>
        <somefield>hello world!</somefield>
        <cloud_events_metadata>
                <type>com.github.pull_request.opened</type>
                <source>https://github.com/cloudevents/spec/pull</source>
                <subject>123</subject>
                <time>2018-04-05T17:31:00Z</time>
                <comexampleextension1>value</comexampleextension1>
                <comexampleothervalue>5</comexampleothervalue>
                <id>A234-1234-1234</id>
                <spec-version>1.0</spec-version>
        </cloud_events_metadata>
</much_wow>
```

But is this possible with cloudevents? Have you guys thought about something like this?

**Comment by afrittoli** [comment]
Thanks @xibz for this. 

In this context I was wondering what the intended use of the different modes in the HTTP binding is https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/bindings/http-protocol-binding.md#3-http-message-mapping

In structure mode, CloudEvents would suffer some a similar problem to the one @xibz mentioned in this issue.
In binary mode the payload is untouched instead, so one option could be for CDEvents to support an equivalent to the binary mode, where all CDEvents data is stored in HTTP headers, and the vendor specific payload is in the HTTP payload.

@n3wscott tagging you here as we already had a chat about CDEvents :)

**Comment by duglin** [comment]
@xibz it seems like @afrittoli is correct in that folks are missing the "binary" vs "structured" modes in CloudEvents. I agree that in structured mode any existing sender or receiver of an event would break if they on a structured CloudEvent, which is why we created "binary mode" where all of the CE metadata is encoded as HTTP headers. Then existing events do not need to change their "body" at all. See this example: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/bindings/http-protocol-binding.md#314-examples

In your proposal, adding CE metadata to the event data, would require all events to support the new metadata under every event's schema and it would require middleware to have access to the event business data in order to do proper routing - which is something CE tries to avoid - and does so in binary mode.

**Comment by xibz** [comment]
I don't think you'd need access to the event's business data. For example, you could deserialize just the metadata portion and do what you want with it. Further every event schema would need to know of this metadata, but isn't that the point of a standard?

Unfortunately, the binary format is also a breaking change. The standard should support various formats that businesses use without breaking the customer. I don't see how any large company would adopt a standard if it requires breaking customers. That just isn't going to work, unfortunately

**Comment by xibz** [comment]
I'll go ahead and close this since the binary format will support one of the proposals :)! Thank you

**Comment by afrittoli** [comment]
@duglin Do you think it would be worth adding some text to the binary mode description to further clarify its purpose?
