### ISSUE TITLE
correlationId

### ISSUE THREAD

**Issue by binishprab** [cloudevents/spec#1088]
We are planning to introduce a correlationId as part of our event messaging to co-relate/group different events together (Kafka Binding)

The CloudEvents spec does not define a standard for using correlation Id.  Just wanted to be sure if there is a plan to introduce it in the future, is it safe for us to use ce_correlationid or maybe just correlation id, given its not part of the spec?

**Comment by duglin** [comment]
We've talked about adding a correlation-id many times but always ended up rejecting it because there are just too many different semantic meaning for it. So, yes feel free to define your own. However, I would suggest that you choose a name that's more specific to your need/domain and not just "ce-correlationid" otherwise you run the risk of conflicting with someone else's extension by the same name (or even a spec defined one if we do ever change our mind) :-)

**Comment by alexec** [comment]
I'm also interested in a standard or convention for this as this is a use case we have. Some kind of URN could allow flexibility. E.g. `{"correlationid": "urn:xxx:yyy"}`.
