### ISSUE TITLE
Conventional Event Carried State Transfer (ECST) Context Attributes

### ISSUE THREAD

**Issue by alexec** [cloudevents/spec#1096]
We need to standardize headers for these two use cases:

For ECST, we need:

* The type of the resource being changes.
* The action being performed on that resource.
* A unique identifier for the resource.
* Optional resource version.

Thoughts?

**Comment by duglin** [comment]
Hi Alex,
1 - re: type of resource - see “[subject](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#subject)”. See the example at the end of that definition
2 - re: action - I think “[type](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#type)” is a good match
3 - re: unique id of resource - see “[source](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#source-1)”, in particular see the example at the end of “subject” again.
4 - re: resource version - this one could either map to “[dataschema](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#dataschema)”, although that is really more about the event itself and not the resource, or you could consider encoding the version of the resource into “subject” since it would seem that version of the resource and type of the resource might be linked in most cases.

Just a thought

**Comment by duglin** [comment]
you have "source" in there twice

**Comment by alexec** [comment]
Ok. That was because of the way my JSON went all wrong. I need to add:

| Name | Desc | Context Attribute |
|---|---|---|
| `asset_id` | An identifier for the software component producing the event. | `source` | 
| `namespace` | The namespace of the resource. E.g. "accounting" vs "mail". | `type[0]` |
| `resource` | The type of the resource being changed. A noun. | `type[1]` | 
| `action` | The action being performed on that resource. A verb. | `type[2]` | 
| `major_version` | The major version of the event type | `type[3]` | 
| `resource_id` | A unique identifier for the resource. | `subject[2]`  |
| `resource_version` | A resource version. | `subject[3]` | 

This software component identifier is useful for events that are signed, allowing the consumer to verify that the producer was allowed to produce the event.

One interesting though here, is that two different software components could produce the state ECST event. The definition of "source" precludes de-duped those two events based on source+id. Maybe this is an edge-case.

**Comment by duglin** [comment]
The table looks good to me.
Your "edge-case" is an interesting one. Yes de-duping from a CE perspective would only catch events from the same "source", and I suspect that knowing which component produced each duplicate event might still be interesting to someone. That then leaves me thinking that the consumer would need to do its own de-duping - perhaps a custom CE extension that acts as a sort of "correlation-id", so regardless of how many components send the same event you'll know its the same one.  ??

**Comment by duglin** [comment]
@deissnerk  @clemensv please add a sample to show how you guys do this mapping.

**Comment by clemensv** [comment]
Azure encodes all context in source and subject and type as needed for routing/dispatch of events across the platform, and the event payload then often repeats some data for the benefit of the receiver. That model proves to work pretty well at our scale.

References:

- https://learn.microsoft.com/en-us/azure/event-grid/cloudevents-schema
- https://learn.microsoft.com/en-us/azure/event-grid/event-schema-blob-storage?tabs=cloud-event-schema
- https://learn.microsoft.com/en-us/azure/event-grid/event-schema-container-registry?tabs=cloud-event-schema
- https://learn.microsoft.com/en-us/azure/event-grid/event-schema-aks?tabs=cloud-event-schema

**Comment by duglin** [comment]
@alexec is this still an issue or can we close it?

**Comment by alexec** [comment]
No. Moved on.
