### ISSUE TITLE
Discuss: `application/cloudevents+json` vs `application/json+cloudevents` vs `application/json` vs ???

### ISSUE THREAD

**Issue by alexec** [cloudevents/spec#1118]
The HTTP binding mandates a non-standard content-type. This is not a `vnd.` vendor type, nor a `x-` type. I get that there is precedent for this in the IANA media types, but I've also seen consumers struggle to unable to parse non-standard content types.  don't expect we'd use this in a production system (or at least allow engineers to choose the content type they receive).

CloudEvents as JSON are just JSON with a schema. 

Comments?

**Comment by clemensv** [comment]
We've not registered with IANA, that's all what makes it "non-standard". If that's the key issue, we can surely fill in the application. Since CNCF doesn't want to be a standards org, I am not convinced that IANA would take it. If that were so, we can also choose to not feel bound by IANA/IETF rules on registration. be that as it may, if you'd like to propose registering the media type with IANA, we can surely go ahead and give it a try.

I think the collision risk is ultra-low and if you have evidence of that struggle consumers may have with things not on the IANA list and yet not being prefixed, I am keen to see it.

- "+json" is defined in RFC6839 for our use-case and it's referenced in https://github.com/cloudevents/spec/blob/main/cloudevents/formats/json-format.md#5-references 

The media type "application/cloudevents" signals that this is a CloudEvent and the suffix indicates the encoding, which is semantically different from "just JSON with schema". We have "application/cloudevents+format" as a pattern and that allows dispatching of CloudEvents even without considering the payload at the dispatcher.
