### ISSUE TITLE
Request to join OpenTelemetry SIG to discuss Events spec - Wednesdays 10am PT

### ISSUE THREAD

**Issue by scheler** [cloudevents/spec#1135]
OpenTelemetry has recently added specification for Events that is in Experimental state now. We would like to align the Events specification with Cloud Events specification. Can someone from Cloud Events spec join the OpenTelemetry Log SIG on Wednesdays 10am PT where the Events spec is discussed? The idea is to discuss and understand the purpose of the two specifications and see how we can align on the data model and semantic conventions on the attributes.

here's the zoom link for the Log SIG on Wednesday 10am PT - https://zoom.us/j/8287234601?pwd=YjN2MURycXc4cEZlYTRtYjJaM0grZz09 
The next meeting is tomorrow 12/14.

For some additional information, OpenTelemetry considers Events as a special form of LogRecord and defines the [semantic conventions ](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/semantic_conventions/events.md)on the LogRecords to identify as Events. There is also an [Events API ](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/event-api.md)to build and emit events.

**Comment by tomkerkhove** [comment]
I like this effort as the Kubernetes events are a pain at the moment (https://github.com/kubernetes/kubernetes/issues/85544)

**Comment by duglin** [comment]
@scheler looking thru those docs, my initial view is that:
- event.domain could map to CE's "source", although it might be nice if it was more specific than just "browser" and had some browser specific info in there. For example, some browser unique ID+".browser" as the value - unless that would be part of the "subject" and it's ok for "source" to be very very generic.
- event.name could mape to CE's "type"

**Comment by jessemenning** [comment]
@scheler , there is currently an active effort within the [OpenTelemetry Messaging SIG](https://docs.google.com/document/d/1dWHhyXnfVife-cQ2DW5-d5Ldp1Lq8Rre2UsHpyo8cEE/) to refine/revise/update the semantic conventions you mentioned in your post.  

After extensive discussion, CloudEvents deferred to the OpenTelemetry messaging SIG for guidance on how to proceed, but is awaiting further feedback and completion of updated standards.  Rather than having CloudEvents participation at Log SIG, it would seem more appropriate for Log SIG to have participation at the OTel messaging SIG.  

I'm part of both communities, so if you have other questions please feel free to reach out.

**Comment by duglin** [comment]
We talked a little about this on today's call and @jessemenning will reach out to the OTel folks to see how best to help out.

**Comment by scheler** [comment]
@jessemenning @duglin I will try and join the OTel messaging SIG next Thursday.  My specific question here was to see if there is even an overlap in use-cases of CE and OTel - which will then dictate how best we can align the two specifications.

I read the meeting notes of [OpenTelemetry Messaging SIG](https://docs.google.com/document/d/1dWHhyXnfVife-cQ2DW5-d5Ldp1Lq8Rre2UsHpyo8cEE/) and my (limited) understanding of it is that they are focusing on troubleshooting of applications using messaging systems and are identifying semantic conventions of tracing for this purpose. It's not clear to me where Events are created in this process. On the other hand the Events spec discussed in OTel Log SIG is to create Events as required by some [use-cases](https://github.com/open-telemetry/oteps/blob/main/text/0202-events-and-logs-api.md#who-requires-events-api). and this is where some of us from the Log SIG felt there could be some overlap with CE and wanted to understand CE further.

**Comment by duglin** [comment]
To me the alignment you're looking for is not so much about potential overlap between CE and OTel, and is really more about "how to turn the OTel events into CEs?". Which is why my comment focused on how the OTel properties might be exposed as CE attributes because that's all it takes to turn things into CEs... just add the appropriate CE attributes to your existing events.

It's best not to think of CE as an "event format" or anything so prescriptive... it's just about how to expose existing event data in a common location. It's meant to be additive to what's already there, not a replacement.

**Comment by scheler** [comment]
Closing this issue. Spoke with @jessemenning and got come clarity. OTel event will evolve independently, and when there is a need to 'turn OTel events into CEs' we will identify the mapping. There is no immediate need now.

Also, from a cursory glance the mapping appears feasible. CE `source` will have to be mapped from OTel `Resource`.

**Comment by tomkerkhove** [comment]
Would you mind elaborating what is missing in CE or why a proprietary format for OTEL is required? (just out of curiosity)

**Comment by scheler** [comment]
@tomkerkhove The OpenTelemetry wire protocol (OTLP) supports only 3 data models (traces, metrics and log records), and so for events we are going to represent them using log records.
