### ISSUE TITLE
Event-data spec when data is too large, so truncated/pruned

### ISSUE THREAD

**Issue by ratankr39** [cloudevents/spec#1136]
Hi team,

I saw both #405, #451 , both kind of tackled this problem but in a different dimension:

What is the recommended way to communicate in the Cloud-event data/attributes spec from Producers point of view, when?
* the event data size is more than 64KB [limit](https://github.com/cloudevents/spec/pull/451)
* Subscribed consumers are expecting that `data` will always be available (or) there is no clear rationale established for missing `data`.
* producer wants to convey that it has either truncated / pruned the data to be in spec limits.

Few options:
1. Define `errors` as an additional data format, where either `data` or `errors` or `both` can be present in an event; While defining this `error` can you also define some form of format for it, i.e. a `http_status_code` or similar is present as `code`, an error message is present as `message` etc?
2. Define `error` as a new optional attribute; this has limitation when we want to provide more than one `error` or `error message` is required.
3. Make `data` also compatible with errors information; this also has limitations to provide 2 schemas for same event-types. It does not scale in my opinion.

**Comment by duglin** [comment]
The 64kb is a min size that must be supported, not max size.
My view on your questions:
1 - I don't think we need to put anything in the event for this. Some protocols (like http) will have a content-length header and that might be helpful to a receiver. But it's optional. Why do you think we need to communicate something in this case?
2 - since the spec doesn't define a mechanism for missing `data`, I believe the assumption is that if there is data for the event then `data` is present, and if it's missing then it's an application level error because the event isn't complete.
3 - if pruning is supported then I think an extension attribute would need to be defined to indicate this - but, again, the spec doesn't have a size limit - other things might though.

To your options... can you elaborate more on what `errors` (either as a format or new attribute) is meant to represent? Is it a way for the producer to tell consumers "here's an event but I generated an error while creating it" ? If so, I'd prefer something along the lines of your 3rd bullet... define an extension to convey additional info about the event. But, I think the event itself needs to still be valid and usable. It's just that the extension says "btw, here's additional info about this event". And the event needs to be process-able even if the extension is ignored. If those criteria can't be met then I think the event should not be generated at all and the producer needs to decide how to deal with that case.... log an error or perhaps there's an event stream to send an 'error event'.

Just my 2 cents

**Comment by deissnerk** [comment]
There is also the [dataref](https://github.com/cloudevents/spec/blob/main/cloudevents/extensions/dataref.md) extension. Its specification states:

> Both data and the dataref attribute MAY exist at the same time. A middleware MAY drop data when the dataref attribute exists, it MAY add the dataref attribute and drop the data attribute, or it MAY add the data attribute by using the dataref attribute.

With this extension it is already possible to provide a download link for the actual data. 

@duglin I wonder if this also violates your expectation that the event should still be usable without understanding the extension. If the `data` is dropped in favor of `dataref` the event looks empty to someone not understanding `dataref`.

**Comment by jskeet** [comment]
That does look like an issue with the `dataref` extension, yes. More discussion required, I'd say.

**Comment by duglin** [comment]
@ratankr39 any comments on the above?

**Comment by duglin** [comment]
Opened https://github.com/cloudevents/spec/pull/1155 to deal with the dataref concern.
Unless/until we hear back from @ratankr39 we'll close this issue with that PR and can reopen if more is needed.
