### ISSUE TITLE
datacontenttype should be an attribute

### ISSUE THREAD

**Issue by gtnicol** [cloudevents/spec#1211]
datacontenttype should be an attribute on the data element, most likely names 'content-type'

**Comment by duglin** [comment]
@gtnicol can you elaborate on how that would work? In XML that's possible:
```
<ce:data content-type='...'> ...data... </ce:data>
```

But in other formats like JSON, it's not as easy since we can't touch the contents of `data` as that's the event itself. Which is why it's a sibling to `data`. And once we treat it as a sibling for other (most?) formats, for consistent it makes sense to do the same for XML.

Perhaps you could elaborate on your motivation of this issue?

**Comment by gtnicol** [comment]
It depends on what you see the actual data model being, and what are the natural serializations of the data model... JSON and XML serializations don't have to be entirely the same, so long as they result in the same data model once parsed. In XML a more natural representation would be as above. I would note that the 'data' prefix on `datacontenttype` seems somewhat redundant.

**Comment by duglin** [comment]
it's funny because we added `data` as a prefix on it to ensure people realized it was describing the content-type of `data` and not something else - like the entire http body (ie. linked it to `data`). 

How would you rework this example?
```
{
    "specversion" : "1.0",
    "type" : "com.github.pull_request.opened",
    "source" : "https://github.com/cloudevents/spec/pull",
    "subject" : "123",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "datacontenttype" : "text/xml",
    "data" : "<much wow=\"xml\"/>"
}
```

**Comment by gtnicol** [comment]
Assuming that ``comexample`` are envelope extensions then something like the following:
```
{
    "specversion" : "1.0",
    "type" : "com.github.pull_request.opened",
    "source" : "https://github.com/cloudevents/spec/pull",
    "subject" : "123",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "payload": {
        "content-type" : "text/xml",
        ... other MIME headers ...
        "data" : "<much wow=\"xml\"/>"
   }
}

```
I'd tend to align with MIME for the headers. In XML, this might be something like:

```
<?xml version="1.0>
<!DOCTYPE event "...">
<event id="..." >
<payload content-type="text/xml">
<![CDATA[
<much wow...
]>
</payload>
</event> 
```
For simple/intrinsic attributes of an event, they could/should most likely go on the event element itself.

**Comment by duglin** [comment]
This topic reminds me of the very long discussions we had around putting extensions into a "bag" vs what we have today, which is extensions sit as siblings to CE defined attributes. One of the discussions at that time was that once you introduce two places to add attributes you then need to have a very clear algorithm to know when an attribute goes in one spot vs the other. And what happens if it _can_ go in either? It became solution that could lead to more problems in the long run as people made different decisions thus causing interop issues. Even in your example, the distinction between payload/mime headers and CE extensions may not be clear to everyone in all cases. There was also the annoyance of having to look at two places instead of one for the metadata - and needing to keep them separate. While there was a "comfort level" associated with the split, in the end it didn't really provide much of a purpose. And btw, many of the same reasons we don't have an extension bag is why they dropped the "X-" prefix on extension/experimental HTTP headers.

In the end we opted for the simple (flat) solution which (while might not be the cleanest from a pure modeling perspective), has served us well. And we took a lot of lessons learned from the simplicity of HTTP headers, which has a good track record as well.

But, while I don't see us changing it but I'm curious if others have some thoughts on the topic.
