### ISSUE TITLE
Propal: Program Binding for CloudEvents

### ISSUE THREAD

**Issue by alexvanboxel** [cloudevents/spec#1220]
Sometimes it makes sense not to have a network binding, but you still want to use CloudEvents. An example would be a step within a workflow dag (for example, a single container executed through Argo Workflows).

Currently, it is not possible to do this in a standard way. A solution would be a new binding specification: "**Program Binding for CloudEvents**." This binding would describe how the CloudEvents and attributes are mapped to _standard in/out and program arguments_.

I've started to take a stab at this, but I like to see if there would be interest in this proposal from the maintainers through this issue.

Use-case example:
* you use a product like Argo Events to trigger your container. Argo Events understands CloudEvents and executes your container. If you follow the example on [Argo Events K8S Object trigger](https://argoproj.github.io/argo-events/sensors/triggers/k8s-object-trigger/), you almost get the desired effect (in the example, the CloudEvent is passed to the program). But if we had a specification for the program binding, the execution of the container would be uniformly described. It could be plugged into other products that support the "Program Binding."

_Note: I don't want to call it Container Binding, as it should not be limited to containers._

**Comment by duglin** [comment]
At a high level, what are you thinking?
Binary mode -> env vars for properties, "data" in stdin
Structured mode -> everything (props+data) on stdin
?

**Comment by alexvanboxel** [comment]
Well, yes... but I was thinking 
Binary mode -> arguments for properties
I wasn't thinking about ENV VARS, iso argument... but now you mentioned this, what would be the better?

**Comment by alexvanboxel** [comment]
ENV VARS is used a lot for passing container-specific secrets, etc. So I'm afraid enumerating the environment variables for discovering the properties could be problematic.

**Comment by duglin** [comment]
I assume by "args" you mean cmd line args... I think seeing something like:
```
myapp CE_Subject=xxx CE_Topic=yyy ...
```
might make people really wonder why we're putting (the equivalent) of env vars as args.

If they're flags, e.g. `--ce-subject=xxx`, then it's a little better, but then you need to require a fair amount of flag parsing in the app.

Plus args stuff runs the risk of interfering with any app defined cmd line stuff (flags, parsing logic....). And I'm not sure all cmd line parsing utils support unknown flag processing, which would be important for CE extensions.

I've seen env vars used (e.g. https://cloud.ibm.com/docs/codeengine?topic=codeengine-subscribing-events#subscribing-events-envvars-job ), and it would align nicely with how they appear as HTTP headers. Doing a loop over them looking for anything that starts with `CE_` should be trivial in any language.

Side note: Env vars for secrets, while done "a lot", upsets security folks since it's not as secure as a mounted volume (or so they believe 😄  ).

**Comment by alexvanboxel** [comment]
Well, I'll work with the environment variables as a starting point for the PR. Thanks for the feedback.

**Comment by alexvanboxel** [comment]
@duglin some pre-PR discussions:

Not all bindings support the return of CloudEvents, but HTTP does. I like to add support for return CloudEvents. But we can't say what the `content-type` is of the returned value. So I see a few options:

1. Always return `application/cloudevents-batch+json`: this also works for a single message (return an array of 1)
2. Always return `application/cloudevent+json`: this means we should drop batch support for this binding
3. Don't support returning of CloudEvents
4. Do something funky, like first returning a type of header block so we can steer the output format: it feels too complex.

I'm leaning towards option 1. This would cover all use cases, with the only downside that the output `content-type` is not always equal to the input `content-type`. (but we would have the same problem with binary mode).

**Comment by duglin** [comment]
I'm leaning towards 1 as well however I think we need to make it clear that returning CEs isn't because this is a request-CE/response-CE flow (even though it could be). Rather, we're defining how to represent CEs on the outbound side of executing an app. It's just a slight positioning statement/difference. I say this because typically events are one-way messages and so having a request/response CE message exchange feels odd. However, if the request was something more like "do you have any events for me?", (polling) then it makes sense to specify how CEs appear as app responses. We just can't stop them from doing CE-in/CE-out if they really want to - nor should we, but we shouldn't position it as the main usecase. IMO.

**Comment by duglin** [comment]
@clemensv @jskeet any thoughts?

**Comment by jskeet** [comment]
Will look next week.

**Comment by jskeet** [comment]
I'm not sure I'd really want to see this as part of the CE spec. It feels to me like if CE defines formats, it's fine for some framework or other to say "Please write your programs to accept a CloudEvent in JSON format from standard input, and emit one on standard output if you want to return an event." That doesn't need standardizing IMO - I think it's unlikely that there'd be multiple frameworks implementing exactly that in a way that programs could easily be written to plug into all of them, as they'd have other command line args etc to conform to.

In terms of whether to return via batch or not, using batch has the disadvantage that we require SDKs to support the single JSON CloudEvent format, but not batches. And it adds a small but non-trivial bit of complexity for the vast majority (I suspect) of event consumers and producers who want 1:1, just to enable the minority of many:many use cases.

**Comment by embano1** [comment]
> I'm not sure I'd really want to see this as part of the CE spec. It feels to me like if CE defines formats, it's fine for some framework or other to say "Please write your programs to accept a CloudEvent in JSON format from standard input, and emit one on standard output if you want to return an event." That doesn't need standardizing IMO - I think it's unlikely that there'd be multiple frameworks implementing exactly that in a way that programs could easily be written to plug into all of them, as they'd have other command line args etc to conform to.

ACK

**Comment by alexvanboxel** [comment]
About the returning CloudEvents, I landed on 3... because only the HTTP binding defined returning of CloudEvents in its binding. And indeed, it adds non-trivial requirements for the simplest use cases where program-binding would be suitable.

@jskeet , @embano1 do I understand I should not continue on the PR for this? I already have this, but then if you don't think it makes sense, I prefer not to spend the time. Here is my WIP (not ready for PR) https://github.com/alexvanboxel/cloudevents-spec/blob/process/cloudevents/bindings/program-binding.md

**Comment by jskeet** [comment]
I'd suggest waiting until Thursday's working group meeting. I definitely don't want to single-handedly shut down an idea, but *personally* I don't think it's worth pursuing to standardization.

**Comment by alexvanboxel** [comment]
> 

I'll freeze working on it. Let me know after the group meeting.

**Comment by duglin** [comment]
> "Please write your programs to accept a CloudEvent in JSON format from standard input, and emit one on standard output if you want to return an event." That doesn't need standardizing IMO

I was ok with this proposal because I do think there's room for multiple ways to expect things. For example, if people use env vars for the properties (in binary mode) should the env vars be upper or lower case? Prefixed with "CE_" or "CE" or not at all? Guidance on when to know stdin is a CE at all via examination of env vars. It's not rocket science, but when there's more than one choice, standards can help. When will there be a `CE_DATA` env var or not? Meaning, are there times when `data` isn't in stdin because there might not be a stdin, but instead part of an env var? (e.g. https://cloud.ibm.com/docs/codeengine?topic=codeengine-subscribing-events#subscribing-events-envvars-job)

**Comment by duglin** [comment]
@alexvanboxel we discussed this on today's weekly call and there was limited interest in moving forward with this at this time. You're welcome to do a PR and hope it might change people's minds, but I think the biggest things that might sway folks is evidence that this is a problem today for folks that needs to be addressed via a stanard.

**Comment by alexvanboxel** [comment]
Thanks, I understand. This thread was already beneficial for brainstorming some of the approaches to take. I will finish the PR for an internal specification. Once we implement it, we can bring the learnings back here.
