### ISSUE TITLE
[Question] How to propose "Protocol binding" for new message broker?

### ISSUE THREAD

**Issue by g41797** [cloudevents/spec#1240]
[Memphis](https://memphis.dev) is new message broker.
It's already [CNCF member](https://www.cncf.io/about/members/)

What is the way to propose **"Memphis Protocol Binding for Cloud Events"** ?

**Comment by duglin** [comment]
Hi. All it takes is a PR 🙂

you can look at a recent PR as a sample: #1233

**Comment by duglin** [comment]
Is this a proprietary protocol?
If so you may need to consider: https://github.com/cloudevents/spec/blob/main/cloudevents/proprietary-specs.md

**Comment by g41797** [comment]
despite the fact that memphis is fork of nats, nats protocol binding can not be used because additional functionality and terminology
It still is not clear what is "proprietary protocol" 
did you mean transport layer?

**Comment by duglin** [comment]
by "proprietary" I mean, is the protocol open-source? And, if it's open-source, does it have a community of contributors or is it really under one company's control? The CE projects makes a distinction between OSS protocols and proprietary ones because we feel it would be inappropriate for us (as a CNCF/OSS project) to promote one company's product. So, if it's "true" OSS then we can add new protocol bindings to our repo, but if it's proprietary then we can add a pointer to the spec instead (via https://github.com/cloudevents/spec/blob/main/cloudevents/proprietary-specs.md ).

Also see: https://github.com/cloudevents/spec/blob/main/cloudevents/primer.md#proprietary-protocols-and-encodings

Does that help?

**Comment by g41797** [comment]
clear 100%
thanks a lot!!!
