### ISSUE TITLE
Might refine the definition of the terminology - Producer

### ISSUE THREAD

**Issue by liuyng0** [cloudevents/spec#1253]
From the [spec](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md), the definition of the producer is
> The "producer" is a specific instance, process or device that creates the data structure describing the CloudEvent.

In my opinion, I don't think the instance, process or device can `create data structure describing the CloudEvent`. The producer just create/emit/issue events. Suggest change it to (given we already have quite accurate definition of the `event`)
> The "producer" is a specific instance, process or device that creates the event.

**Comment by liuyng0** [comment]
Also, looking into the definition of the Source, it's sounds vague.
> The "source" is the context in which the occurrence happened. In a distributed system it might consist of multiple [Producers](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#producer). If a source is not aware of CloudEvents, an external producer creates the CloudEvent on behalf of the source.

`The "source" is the context in which the occurrence happened`, I assume this context here is not [the Context](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#context). Do we want to express it as `the subject from where the occurrence happened`

**Comment by duglin** [comment]
@liuyng0 I'll bring this up on this week's call. Just a couple of comments:
- I seem to recall that we did struggle a bit on the terminology and for "producer" and I believe we decided that it would be the entity that created the CloudEvent not the underlying event itself. While they certainly could be the same entity, the spec really has no control over the "event producer", all the spec can control is the "CE producer". Hence the wording. We may have missed some spots from a consistency perspective, but this is my recollection. Notice that in your 2nd comment you quoted this `If a source is not aware of CloudEvents, an external producer creates the CloudEvent on behalf of the source`, which I think is consistent with my memory.
- re: `source`, I'm not following your suggestion since we already have `subject` field. If it helps to think of it in a concrete use case, I tend to think of "source" as the S3 bucket that changed (it's the context, the "where" the event happened), and the "subject" is the entity acted upon by the event - in this case the S3 blob/file. But I'm probably not fully groking your concern.

**Comment by duglin** [comment]
Agreed to CWNA on the 3/21 call
