### ISSUE TITLE
Extension names become case insensitive in binary encoding

### ISSUE THREAD

**Issue by inlined** [cloudevents/spec#177]
Extensions are not defined to have case-insensitive names, but the binary encoding puts the extension name in a header. Since header names are case insensitive, their case may be changed by middleware. This makes extensions fairly fragile.

I suggest we either:
1. Define extensions to be case insensitive in spec.md
2. Change the way extensions are encoded in HTTP binary encoding.

I personally prefer (2). I'd recommend

```
CE-X: <key>: <value>
```

**Comment by tjanczuk** [comment]
+1. 

This problem makes it impossible to implement a compliant consumer in some popular frameworks. For example, the Node.js HTTP implementation explicitly normalizes all HTTP headers to lowercase.

**Comment by duglin** [comment]
I'd prefer a solution that didn't treat extensions any differently from spec-approved attributes. Is there an issue with having the same rules for both?

**Comment by inlined** [comment]
We could just have a single header CE-Extensions that is a map of all extensions? I think labels are also something that we might want to put in headers always and use the same sort of repeated header rule for easy filtering by gateways.

**Comment by duglin** [comment]
A single header would be ok as long as the extensions are actually modeled as sub-properties of something. E.g. if in JSON they were:
```
"extensions": {
  "foo": "bar"
}
```
If we allowed extensions to be top-level json properties then they're more akin to siblings of spec-approved attributes and I would prefer for them to be individual http headers.

Yes, I'm still hoping to convince people we don't need a formal "bag" defined and we can just use normal json (or whatever) extension mechanisms.  :-)

**Comment by technosophos** [comment]
Encoding the header values with base64 will allow easy parsing

In pseudo-code:

```
CE-X: BASE64(name: value)
CE-X: BASE64(name2:value2)
```

Which then easily meets the HTTP spec's header collapsing rules as:

```
CE-X: BASE64(name: value), BASE64(name2: value2)
```

Other options include:

- use multi-part MIME bodies and store extensions in one part
- Using query strings (which has some interesting consequences)
- defining an encoding format for extensions that are embedded in headers
- requiring strings to be map[string]string instead of map[string]any

**Comment by duglin** [comment]
See: #225

**Comment by duglin** [comment]
This topic came up on the SDK call yesterday. I'm wondering if we need to do anything about this at all from a spec perspective. Meaning, we're just following HTTP and treating the headers as case insensitive.  How they get mapped in the tooling is up to the tooling. (punt!)

So , in the case of extensions, I would think that in most cases the tooling would just put them into some kind of map. Is the solution here anything more complicated than the tooling (sdk) be clear about what it does with them?  For example, perhaps we decide that our SDK lower-cases all extension names so they're easier to find?  It could them then "as-is" but I think that's a bit harder for app to deal with.

**Comment by duglin** [comment]
One of the reasons we created the raw/binary format was because we wanted a format that avoided the JSON parser if all you wanted was the CE properties - for faster parsing times.  If we base64 encode the properties it seems we're losing that benefit.

I still don't see the issue with the spec being agnostic about this - just let the protocol spec (e.g. http) define how properties are serialized, and separately let the SDKs decide how they will present extensions to their users. If the protocol is case in-sensitive then I think the SDK should lowercase them - but that a decision it can make for its users.

**Comment by cneijenhuis** [comment]
> Does the spec say (don't recall seeing this) that properties (built-in or extensions) be English words?

Somewhat, the [naming convention](https://github.com/cloudevents/spec/blob/master/spec.md#attribute-naming-convention) says the goal is to:

> ... aid integration with common programming languages

While that doesn't necessarily imply English words, I wouldn't choose the full Turkish Alphabet for names (to stick with the example of @timbray).

What do you think of limiting attribute names to alphanumeric characters (I already proposed it here: https://github.com/cloudevents/spec/issues/265#issuecomment-416177462)? That should make life easier for SDKs, and also for the HTTP binding (e.g. it could convert camelCase to snake_case).

**Comment by PerryBirch** [comment]
UTF-8 seems to me more Payload and Presentation concerns rather than wire protocol where it's mostly machines talking and operators just want a bit of visibility

**Comment by duglin** [comment]
on the call today we agreed to close this issue - we can reopen if new info comes up.
