### ISSUE TITLE
Do eventType, eventID describe the type and identity of events, or occurrences?

### ISSUE THREAD

**Issue by ljnelson** [cloudevents/spec#188]
The specification [says of eventType](https://github.com/cloudevents/spec/blob/v0.1/spec.md#eventtype):

> Type of occurrence which has happened.

But then it [says of eventID](https://github.com/cloudevents/spec/blob/v0.1/spec.md#eventid):

> ID of the event.

As a reader, I had a bit of cognitive dissonance here.  The spec [goes to some lengths to indicate in its terminology section that an occurrence is not an event](https://github.com/cloudevents/spec/blob/v0.1/spec.md#occurrence), but is contained by one, but then here seems to conflate the two again.

**Comment by duglin** [comment]
@ljnelson are you suggesting that "eventType" should really be called "occurrenceType" ? If not, can you give a concrete proposal for what you think should change - that would help me more fully understand the "cognitive dissonance" you're experiencing  😄

**Comment by ljnelson** [comment]
Thanks for replying, @duglin.

I am saying that I don't know from the specification.  Is it the intent of the specification that eventType should describe the type of an event?  Or should it describe the occurrence the event describes, which according to the definitions and cardinalities expressed by the specification might be described by many events?

If:
* eventType is actually supposed to describe the type of the _occurrence_, and
* one occurrence is designed to be potentially shared (semantically) among several events, and
* the specification wishes to define both the term event and the term occurrence as it does today

…then yes, among the things I'm suggesting is that eventType be renamed to occurrenceType.

(Personally I'm not clear on why there are so many terms that have been introduced into the specification.  Do we really need to define occurrence and context in particular?  Can't we just define an event and the data it carries?  Then a lot of these issues go away it seems to me.  If not, then IMHO we need to take great care in being extraordinarily specific about modeling the objects involved.)

(In this issue I'm setting aside issues raised in #186 and #187 about the fuzziness with respect to an event's context, and whether its attributes such as eventType, eventID and eventTime should properly be called _event_ attributes, rather than _context_ attributes (can an eventID really be shared between two events?!); there's still specification ambiguity there IMHO that might or might not be resolved if renaming eventType to occurrenceType takes place—for example, if it is now occurrenceType, then maybe ambiguity about whether it is part of an event or part of an event's context goes away.)

**Comment by inlined** [comment]
Oooh boy. This is bringing back a very long discussion we had internally at Google. Here are the litmus tests for those who want to jump in. I think solidifying our intuition on what the term means will help us argue what its name should be:

1. I have two functions listening to Google Cloud Storage events: one for thumbnailing and one for recognition. Do these functions get the same or different `eventId`s?
1. When I upload a file to Google Cloud Storage that overwrites a file, that triggers a `google.storage.object.finalize` and either a `google.storage.object.archive` or `google.storage.object.delete` (depending on bucket config). If I have a function listening to each, do they get the same or different `eventId`?
1. When I listen to the Firebase Realtime Database, you can listen to strict events (create, update, delete) or catch-all events (write). Should a listener to create and a listener to write get the same `eventId`?
1. The Firebase Realtime Database is fairly unstructured; think of it as a JSON tree and you can listen to events for any changes at any node of the tree (plus its children). If I have one function listening at `/users/{userId}` and another listening at `/users/{userId}/profile`, should the two get the same `eventId`? (note: the data will be different, because it's rooted at the listener)
1. [somewhat out of scope of this spec] If I have a fraud detection system that has two logging event subscriptions: one for 1% of all traffic and one for traffic coming from any resource with an "audited" label. Do 1% of events from resources with an "audited" label get delivered twice?

**Comment by ljnelson** [comment]
Perhaps some pictures will help.  I sent some out-of-band email to @duglin on this subject but I'll try to super-condense it here and make it relevant only to this issue.

In the following diagrams, boxes represent _concepts_, not any kind of implementation artifact.  That's critical.

I also define (for the purposes of this discussion and none other) a distinction between a first-class concept, which is one with attributes, and a…er…non-first-class concept 😄 which is something that perhaps has to be sketched in the specification, but contains no attributes.  Again, we're talking spec constructs here, not code.

With that, here's what the specification on the master branch as of this writing looks like using simple UML notation, robotically translating nouns into boxes, lines and text:

![image](https://user-images.githubusercontent.com/80764/39828539-46d21268-5370-11e8-8b9c-cd3a4095aac2.png)

So: two `Event`s may share a single `Context` (as @duglin [indicated](https://github.com/cloudevents/spec/issues/187#issuecomment-387735296) in #187.  If that's true, then `eventID` here can't be used to deduplicate events, and, I hope people realize, looks odd hanging out there in `Context`-land.  So do `eventTime`, `eventType` and `eventTypeVersion`.  I highly doubt this is the state of affairs the specification meant to define.

So, OK, reading the specification as sympathetically as possible, maybe it's _trying_ to say:

![image](https://user-images.githubusercontent.com/80764/39828653-a6c5c250-5370-11e8-9bfa-9b47af204eff.png)

…but it does not in fact say this.  Here, an `Event` is a first-class concept (with attributes).  In the specification it is not (all attributes are attributes of a `Context`).  Also, here, `Occurrence` remains a non-first-class concept.

OK, perhaps instead what was meant was something more like:

![image](https://user-images.githubusercontent.com/80764/39828693-d456c5ca-5370-11e8-8955-c71d05350b94.png)

Here, you can share a `Context` between `Event`s, and even `Occurrence`s between events.  We've moved `eventID`, `eventType`, `eventTypeVersion` and the like to `Occurrence` because we're guessing that perhaps what was intended was that these things should describe the `Occurrence`s, not the `Event`s that describe those `Occurrence`s.  (After all, the specification takes great care to distinguish between an `Event` and the `Occurrence` it describes.)

Finally, if sharing `Occurrence`s isn't quite right, you can refine the model above to this (concepts, not code, remember):

![image](https://user-images.githubusercontent.com/80764/39828790-245ef5c4-5371-11e8-85f3-967a35f83682.png)

…which now says that a `Context` is something that describes an `Occurrence`, and an `Event` serves to house the `Context` and the event data.

So my issues (#186, #187 and #188) and certainly #119 are all related to these pictures I think.  I'm trying to figure out which picture was intended.  I don't have enough background to propose which one is better; I'm just trying to understand what's written.

**Comment by duglin** [comment]
@ljnelson I tend to agree that defining less terms is a better approach, because the more you try to define the more you.....well, have to define ;-)   and differentiate between them. And, as you said, if you don't get it right then it could lead to confusion for those who are very pedantic about that kind of stuff.  As I mentioned elsewhere, I'd be happy with just a CloudEvent being made up of "event data" and "event metadata".

As for @inlined's comments/questions... to me they're all out of scope as of now.  Since we don't even say that an EventID *MUST* be unique (we leave it as an impl detail), it re-enforces to me the idea that our spec is staying out of the business of telling people how to construct, or even process, CloudEvents. This is why whether or not the same set of content attributes (errr event metadata) appears in more than one CloudEvent is not our concern - to me anyway. That's for something above us to worry about.

**Comment by ljnelson** [comment]
@duglin I agree with the spirit of what you're saying: fewer terms in an ontology is always better.

But words matter, and no more so than in specifications (unless you like Github issues 😄 ).

The specification today defines _lots_ of terms in what is a rather large and disjointed ontology (yes, I'm one of those pedants 😄 ).

So if the spirit of the specification is as you say, then perhaps it should simply look like this:

![image](https://user-images.githubusercontent.com/80764/39829186-72048b3a-5372-11e8-851c-80a0ad28e15c.png)

Then: if it ain't in a box, it ain't in the normative part of the spec.  Personally I think if this is really what you _intend_, then this is what should be written. 😄

**Comment by ljnelson** [comment]
(I've closed #186 and #187 in favor of this issue, which has become the important one and has subsumed their concerns.)

**Comment by duglin** [comment]
that's pretty much the mental model I have

**Comment by ljnelson** [comment]
OK, then perhaps drop definitions of and references to occurrence and context and context attributes in the specification, and move context attributes to a first-class event concept?

**Comment by duglin** [comment]
I personally wouldn't object with that direction, but I would wait until you hear from others since I suspect some folks really like all of those terms being there

**Comment by ljnelson** [comment]
Sure; [spitballing a hypothetical `definitions.md` over here](https://github.com/ljnelson/spec/blob/spec-rewording/definitions.md) for perhaps later selective inclusion.

**Comment by evankanderson** [comment]
Hey, I was just thinking about this today, and I came up with an _interesting_ thought exercise.

Imagine a source (a graph database) which provides the ability to register a "watch" on certain types of update events. The watch registration takes parameters including a set of credentials which are performing the watch, and a destination for delivery. The `Event`s delivered to a watch destination contain a `Data` payload which includes references to objects connected to the updated object. In order to avoid leaking the existence of objects, _the set of object references (and thus the `Data` of the Event) varies based on the supplied credentials_.

In https://github.com/cloudevents/spec/issues/188#issuecomment-387810009 diagrams (thanks!), this would be different `Data` in an event which seems to share the same `Context` and `Occurrence`. In this scenario, what would the `EventID`(s) be for two different messages with different `Data` about the same `Occurrence`?

It would be good to explain the rationale for whichever recommendation we make:
* If `EventID` is really an occurrence ID, then it should be possible to join events from two different points of view (say, an insider-risk view and a large-accounts view) after separate analysis.
* If `EventID` is an occurrence ID, that also means that it's unsafe for any downstream system to de-duplicate messages based solely on `EventID` without also taking into account the rest of the payload.

I think this is somewhat isomorphic to concerns raised in @inlined 's comment; in particular, a single API call (occurrence) may generate multiple `Event`s (i.e. the "overwrite in storage" generates both `object.deleted` and `object.created`). It seems germane to the spec to provide some guidance as to whether the `EventID` can be used to distinguish between sequential `object.deleted` and `object.created` calls and a single overwrite call.

**Comment by duglin** [comment]
In thinking about this one again, a couple of things come to mind:
- what is the relationship between an occurrenceType and eventType?
- Any single occurrence might result in multiple events - I think everyone agrees with that.
- Does that mean that all events from a single occurrence MUST have the same eventType? I don't think so - or at least that's out of scope for our spec to mandate.
- So, this means that it's very possible that occurrenceType != eventType when someone converts an occurrence into an event.
- This might lead me to conclude that the description of "eventType" should not say "Type of occurrence which has happened." but instead say "Type of **event** which has happened." - however, events do not "happen" - they are a manifestation (or description) of an occurrence. So, I'm leaning towards keeping "occurrence" in there as it feels more accurate.

But, having said all of that, I do kind of wonder if we're thinking too much about this and I question if it really matters. :-)  Regardless of which word we use, would it cause an interop problem? Would anyone not know what the intent of "eventType" really is if we picked the wrong one?

@ljnelson perhaps what's needed here is to replace:
> Type of occurrence which has happened.

with:
> Events are generated as a result of occurrences. This attribute contains a value describing the type of event corresponding to the originating occurrence.

This links the two, but allows for the fact that there could be some kind of mapping/conversion taking place during the Event-ifying of things.

**Comment by duglin** [comment]
@ljnelson any more thoughts on this one? Is this still a concern?

**Comment by ljnelson** [comment]
Hi; thanks for pinging me.  I've been away from this spec for a long time so will refresh.  Your [comment above](https://github.com/cloudevents/spec/issues/188#issuecomment-434281078) is certainly headed in the right direction as far as I'm concerned.
