### ISSUE TITLE
receipt-queue context attribute

### ISSUE THREAD

**Issue by lfourie** [cloudevents/spec#28]
This is a proposed metadata attribute (from Context Attribute Backlog):

receipt-queue
    Type: String
    Description: An optional return endpoint for completion events

**Comment by duglin** [comment]
This feels like something more akin to "event orchestration". Something that might sit on top of our spec, not but direction part of our spec. What do other's think?

**Comment by sslavic** [comment]
Reminds me of NATS Request-Reply https://nats.io/documentation/concepts/nats-req-rep/

**Comment by duglin** [comment]
I'd like to propose that we close this with no action. At best, based on all of our discussions, I think something like this would end up being an extension - and as such I'd like to wait until we hear from the community that there's a lot of requests for this to be defined. Then we can reopen.  Thoughts?

**Comment by duglin** [comment]
On the 6/7 call we decided to keep this open since we may want to define it as an extension.

**Comment by duglin** [comment]
is #218 related to this?

**Comment by duglin** [comment]
Given we now have a ParitionKey extension, can we close this one?

**Comment by clemensv** [comment]
What is a "completion event"? 

If you're raising an event, you don't instruct anyone else to do something, but you tell subscribers about something you did. 

"Completion" implies that there's an expectation by the publisher that something gets done. That's a job and not en event. If we just run jobs through an eventing-oriented pub/sub system that raises quite a few questions: How many parties may do the assigned work? How often may the work get done? Can/should the work again be performed when the events are replayed? What happens when "completion" doesn't happen?

There are also communication challenges here and at the level of abstraction we're operating on with CloudEvents: How do you ensure that the receiver can reach the given endpoint? How do you ensure that the responder even speaks the desired protocol given that we have choices? How does the responder authenticate/authorize at that endpoint? 

This also conflicts with our core event definition: "The routing can be performed based on information contained in the event, but an event will not identify a specific routing destination."

**Comment by duglin** [comment]
Agreed to close on the 6/13 call.
