### ISSUE TITLE
Context attribute naming consistency

### ISSUE THREAD

**Issue by JemDay** [cloudevents/spec#323]
In last weeks call a comment was made (Tim from AWS?) relating to the potential for renaming some of the context attributes; i thought it would make sense to raise it for discussion here prior to opening what would be quite a large PR.

The proposal (as i understand it) would be to rename along these lines:

| Current | Proposed |
| --- | --- |
| eventType | type |
| cloudEventsVersion | version |
| eventID | id |
| eventTime | time |

An alternative argument might be to ensure all context attributes follow a consistent naming structure, eg :

| Current | Proposed |
| --- | --- |
| eventType | eventType |
| source | eventSource |
| data | eventData |

**Comment by rperelma** [comment]
@JemDay: see https://github.com/cloudevents/spec/pull/321/

**Comment by duglin** [comment]
+1 to the idea of being consistent.

I'm torn on which I would prefer though. Not having "event" there is nice because it feels repetitive to say "event" when its already on an "event" resource. However, we're asking extension authors to be descriptive with their new properties to avoid conflicts - shouldn't we do the same? As an example, "id" is pretty generic and I can certainly see someone adding another "id" type of extension at some point - so would we prefer to see:
- `id` & `fooid`

or
- `eventid` & `fooid`

in the same message?  I guess I'm learning towards putting "event" on each :-)
