### ISSUE TITLE
Extension for Distributed Tracing is a Draft

### ISSUE THREAD

**Issue by fabiojose** [cloudevents/spec#347]
I have requiremens to implement event tracing with CloudEvents spec. I read the docs and found the distributed tracing in the extensions.

[Distributed Tracing](https://github.com/cloudevents/spec/blob/master/extensions/distributed-tracing.md)

Then I read the [spec](https://w3c.github.io/trace-context/) from W3C. 

The stage of spec, that is a draft right now, for Distributed Tracing could be an issue to implement in my use cases?

**Comment by duglin** [comment]
@fabiojose if I understand your question, that decision is really up to you. It is always a risk to implement a specification while it is a draft due to the fact that it might change before it reaches its v1.0 version. However, if that spec is of interest to you, I would recommend trying to find a way to implement it (even if just as a proof-of-concept, not in production) so that you can provide feedback to the authors. It would be a shame to not find out about a significant issue until after the spec is finalized.

**Comment by fabiojose** [comment]
Fine! thanks @duglin
