### ISSUE TITLE
How should we deal with Deprecated events

### ISSUE THREAD

**Issue by mbernard** [cloudevents/spec#365]
It would be nice to have a way to tell the consumer  that an event version is now deprecated or will be in the futur
That way, they can subscribe to a new version of the event.

Do you think this should be part of an extension?

**Comment by Tapppi** [comment]
I think an extension would be appropriate to address the acute issue and then we can see where it goes. A normalised way of notifying consumers of deprecation "on the line" would obviously help them set up alerts on deprecations more easily, even if all producers don't support the extension (at all or in the same exact way). The downside, or worry, is that we would prescribe too much convention before the _"broader solution"_ @duglin referred to gets even a chance of trying to formulate something in this area.

Because of the fine line we'd have to walk here, I think the extension should be merely a well-known, but loosely defined, attribute. More formally, the extension:
* should define a common attribute for signalling deprecation
* should not require prescribed meaningful content for the attribute
* could define a way of discerning different content, for example through an auxiliary attribute similar to [the `sequenceType` of the sequence extension](https://github.com/cloudevents/spec/blob/master/extensions/sequence.md#sequencetype).

**Comment by duglin** [comment]
of those who spoke up, it seems an extension might be the preferred choice (if we do anything). Would someone want to take a stab at a PR to force the discussion/decision?

**Comment by Tapppi** [comment]
@duglin I'll try to make a proposal for an extension, but we'll see whether I have cycles before next weeks call.

**Comment by duglin** [comment]
@Tapppi thanks a ton!!

**Comment by duglin** [comment]
@Tapppi or anyone else... still interested in this?

**Comment by duglin** [comment]
I'm going to suggest we close this since no one seems to have any interest in coming up with a proposal.  Please speak-up before Thursday if you'd like to see it remain open

**Comment by duglin** [comment]
Agreed to close this on the 10/10 call
