### ISSUE TITLE
System Architecture diagram / document explaining the context for events

### ISSUE THREAD

**Issue by ultrasaurus** [cloudevents/spec#37]
We would like to write up some info so that folks can arrive at this repo and understand what kind of event system we're talking about.

Starting docs:
- [presentation](https://onedrive.live.com/view.aspx?resid=123CCD2A7AB10107!744659&ithint=file%2cpptx&app=PowerPoint&authkey=!AIUYJmTPLT_D9Os) -- slide 23 (below) shows the difference between general messaging, and "Eventing" which is what CloudEvents is focused on.  Events are statements of fact.
![image](https://user-images.githubusercontent.com/41906/36404501-e05bbfa6-159f-11e8-87a6-7495b5ff0d18.png)
- https://github.com/cncf/wg-serverless/tree/master/proposals/cloudevents
- [Cloud-Native Event Mapping (CNEM)](https://docs.google.com/document/d/1dFfnWnbRDTvGwpwaBsvXRlw0ZyL3xYl7iXhYqbAPJjk/edit#heading=h.a30wdiuh8lnh)
- [Common Event Use Cases](https://docs.google.com/document/d/1E9J3yPIoqtjVKdDe7f3p7RxJml57Dc64T4b3o445cYk/edit)

- [OpenWhisk](https://openwhisk.apache.org/) has a nice illustration of the kind of system we're talking about CloudEvents:
![image](https://user-images.githubusercontent.com/41906/36404396-3acb2608-159f-11e8-9dda-6f4b2593f649.png)

Assigned to: @ultrasaurus @yaronha

**Comment by duglin** [comment]
@ultrasaurus you ok with owning this one?

**Comment by duglin** [comment]
Perhaps including the current "Reference" section of the spec (where we show what some providers do today).

**Comment by ultrasaurus** [comment]
@duglin I think you can assign multiple owners.  Yaron volunteered to help, but I don't know his github!

**Comment by duglin** [comment]
Took a sec I managed to hunt him down @yaronha :-)

**Comment by duglin** [comment]
@ultrasaurus I like what you have so far, and I like that it appears you used a lot of the same text we have in the spec itself. That consistency will help newbies.

I don't think there will be much disagreement, or discussion, around slide 1-4 since those appear to be directly from the spec - so any disagreement on those should probably be addressed via PRs to the spec. Slide 5 (definition of 'action') is new and while I suspect is out of scope for the spec (since we're just defining the shape of events, not the processing model), I do think that talking about actions in a system architecture doc will probably help people understand the complete picture.

w.r.t. format of the output of this work, I'd prefer an md file, once we have a baseline doc, so its easy for people to issue PRs against it.  But to get to the point of having a baseline/initial-draft, I think a google doc might be easiest.

**Comment by duglin** [comment]
@ultrasaurus are you still interested in working on this one?

**Comment by duglin** [comment]
I'm going to suggest that we close this one since I think our primer doc covers our design/architectural thinking for how to use the spec and why we made the decisions we did.  Plus we'll continue to add more text over time.

**Comment by deissnerk** [comment]
@duglin I agree. By now we are also in a working mode that people create specific PRs, if they feel that something is missing.

**Comment by duglin** [comment]
Agreed to close on the 6/13 call.
