### ISSUE TITLE
if schemaurl is a uri-ref, how do I get it?

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/spec#394]
Suppose I get a cloudevent with a `schemaurl` set to `/spec/v0.1/data/schema/events.json`

This is valid from the specs point of view. But from an event consumer, they are out of luck to know how to fetch that schema data.

**Comment by cneijenhuis** [comment]
This (or at least a variation of it) was previously discussed here: https://github.com/cloudevents/spec/pull/169

The argument made by Clemens is that if the eventtype is e.g. `Microsoft.Storage.BlobCreated`, you as an event consumer interested in this event will (be able to) know the base-url for fetching the schema.

**Comment by n3wscott** [comment]
Sounds like the assumption is we will need top special case a lot of code to be able to understand payloads. 😢

**Comment by deissnerk** [comment]
The same is true for the source uri. Some sources will only have relative uri references and others may be absolute with schema and authority etc. So some events can be routed based on authority, while for others the authority is kind of hidden in the event type or some other context.

**Comment by n3wscott** [comment]
This makes sense for `source` because `source` is just metadata about the entity that produced the event, but `schemarul` is provided for the consumers benefit to understand the payload. And yet... they can not. Also, schema**url** is a _uri-ref_ 😕

**Comment by deissnerk** [comment]
I understand that it's especially unfortunate because of the **url** part, but `source` is a piece of metadata that needs to be handled generically by middleware. A well-defined way for de-referencing relative uri references would be helpful. Otherwise you might end up with "if-then-else" logic in event routers.
I realize that this is off-topic in this issue, though. 🤔

**Comment by duglin** [comment]
My comments are broader than this one attribute so sorry for the tangent but I think it's relevant here too.

I think it's important to distinguish between the spec's goal of promoting machine processable CEs and mandating them. By this I mean, the spec provides the guidance for event producers to create CEs that are well defined and do things like have de-reference-able URIs (when appropriate) and reverse-DNS-named sources, etc...  All of these types of things will help ensure there isn't conflicting fields between event producers and that machines can introspect the CEs to perform some cool processing on them w/o the need for too much producer-specific hand-crafted code. 

However, I don't think the spec can mandate these things, nor should it - at least not yet. There will be times when either that level of detail just isn't available nor desired for certain environments.  And that's ok. Yes it may mean that sometimes the event consumers will need to have a priori knowledge about the event producer being used, and that's ok. There is still value in using CE.

Let's take a concrete example by using the `type` attirbute and github events as defined at https://developer.github.com/v3/activity/events/types/
Those are clearly not reverse DNS names (e.g. CheckRunEvent), and that's unfortunate. However, that's what we have to work with. As a result, to ensure some level of consistency for the user developing an application that will receive a CE-wrapped github event, I would recommend that the `type` field be `CheckRunEvent` since that is what is listed in the Github docs and therefore what the user would expect to see. No, it's not a reverse DNS name and therefore not 100% ideal, but I think that offers a nicer UX than asking them to perform some mapping between what they read in the Github docs and some CE-proxy/middle-ware specific mapping that can only decrease portability of their code.

**Comment by duglin** [comment]
@n3wscott what are you current thoughts on this one? Do we still need to make a change or are you ok with the current wording in the spec?

**Comment by n3wscott** [comment]
I think we can live with the current spec and see what happens.
