### ISSUE TITLE
contributors list

### ISSUE THREAD

**Issue by ultrasaurus** [cloudevents/spec#42]
It would be really helpful to have a list of contributors, to solve two problems:
1. Associating folks who attend Serverless WG meetings with their github username
2. Who is involved in Eventing and is interested in using the CloudEvents spec in some way

Assigned to: @ultrasaurus

**Comment by ultrasaurus** [comment]
@ac360 -- do you have a reference to the folks who contributed to the original draft via Google doc?

**Comment by duglin** [comment]
In other specs I've seen a list of authors/contributors in the spec, but most of those were specs in pre-github times.  I suspect most people just look at the github history to get that info.

re: associating WG people with github names, I can add a column to: https://docs.google.com/spreadsheets/d/1bw5s9sC2ggYyAiGJHEk7xm-q2KG6jyrfBy69ifkdmt0/edit?pli=1#gid=0

**Comment by duglin** [comment]
all - I added a new column to https://docs.google.com/spreadsheets/d/1bw5s9sC2ggYyAiGJHEk7xm-q2KG6jyrfBy69ifkdmt0/edit?pli=1#gid=0 ping me via slack if I couldn't figure out your github ID or if I got it wrong.

**Comment by ultrasaurus** [comment]
My thinking is that we will want to encourage people to contribute use cases, documentation, and other contextual materials, in addition to the folks that directly contribute to the spec.  

If we create a way for people to submit their info via PR, then this will also enable more async participation.

**Comment by duglin** [comment]
Conceptually, sure we want people to contribute to all of our docs. And people can do that via PRs. I'm just not sure what you're suggesting we do since everything is out in the open and people can (and are) already doing what I think you're looking for.  For example, once @ac360's PR ( https://github.com/cloudevents/spec/pull/8 ) is merged, we'll have a "use-cases.md" file and I expect people to file PRs against that pretty quickly.
