### ISSUE TITLE
Revisit PR 218 to see if partitionkey extension is still needed

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#430]
See: https://github.com/cloudevents/spec/pull/218

Once the Kafka transport PR ( https://github.com/cloudevents/spec/pull/337 ) is resolved revisit the decision to add the partitionkey extension - it might not actually be needed, and if not the group should consider removing it per the discussion in #218.

**Comment by bluemonk3y** [comment]
I have seen cases where the partitionKey information is not part of the payload and cases where it is. I can also see a case where a partitionKey might be augmented with a partitionKeyExtractor function; to rewrite the partitionKey or even replace it to allow for data-stream collocation or data distribution purposes. 

Pros and Cons when removing the partitionKey.

Pros:
1. Potentially pushes down transport concerns during Cloud Event generation where key extraction will work without payload modification
2. Reduces the number of Cloud Event spec attributes

Cons:
1. Potentially force the producer to be aware of transport concerns (i.e. when embedding the partition key data)
2. Potential overhead and secure-key access where a secured data payload is concerned

**Comment by duglin** [comment]
@hschaffner ^^^

**Comment by clemensv** [comment]
Can we close this?

**Comment by duglin** [comment]
based on what @hschaffner said on the previous call, yes I think we can. Heinz let me know if I'm remembering incorrectly.

**Comment by hschaffner** [comment]
Clemens:

As I mentioned a while back you can close this.

My concern was that adding the optional field for a partition key was not really applicable to the CE specification. With Kafka the key is part of the payload since Kafka records are name/value pairs. The optional key is part of the payload, but like the Kafka Topic it is defined at transport binding. It really is not really part of the CE Spec for the object definition just like Topic, Exchange  or Queue name for other transports.

However, if you want to add it as an optional header, I have no issue, however, it is unnecessary.

This is part of my general concern of adopting things into the spec that are not generally applicable. Another case in point is the Avro serialization as an alternative to the structured JSON payload. Avro is predominantly used for Hadoop V2 and because of the early relationship it has been adopted by Kafka. But do you need another structured  payload and serialization defined? Especially when it is so limited in focus? Even more interesting by the fact the Kafka library already supports a bi-directional Avro/JSON conversion?

Heinz
