### ISSUE TITLE
Replace/remove Tracing extension in favor of OpenTracing

### ISSUE THREAD

**Issue by zihotki** [cloudevents/spec#487]
It may be benefitial to consider to remove [Tracing specification extension](https://github.com/cloudevents/spec/blob/master/extensions/distributed-tracing.md) from CloudEvents specs and refer to [OpenTracing](https://opentracing.io/) instead which is in incubation stage at CNCF. It's much more mature and widely adopted so it makes sense to me to embrace it here as well. Although it may require to adjust CloudEvent specs but this way it'll make possible to use all tooling built for OpenTracing.

**Comment by duglin** [comment]
@zihotki would you be willing to submit a PR for this? I don't see a reason why we can't have both extensions available :-)

**Comment by clemensv** [comment]
That extension is for the W3C trace context spec, which is a standard and is gaining momentum. There is a mapping https://github.com/opentracing/specification/blob/master/rfc/trace_identifiers.md

**Comment by duglin** [comment]
@zihotki does that answer your question?

**Comment by zihotki** [comment]
@clemensv AFAIK the new buzzword is [Open Telemetry](https://github.com/open-telemetry/opentelemetry-specification) which should unite Open Tracing and Open Census, and probably W3C's Trace Context. 

@duglin Yes and no. It makes sense that it's an extension for W3C Http Tracing specification but it's not clear from the name of the extension which currently is "Distributed Tracing Extensions" which is too generalized in my opinion given there are more than 1 standard. 

But there is another conceptual and practical reason why it's better to leave it aside. Tracing/telemetry are better to be solved on the transport/infrastructure level, not on the message/event level. And given that a programmer is going to use an existing SDK for his tracing specification of choice, that SDK is already providing integrations with a plenty of transports on the lower level than CloudEvents. So this extension seems to be quite redundant.

Not to mention that currently it's specifying that in-memory it's represented by **distributedtracing** key and on the transport it's represented by 2 keys - **traceparent** and **tracestate**. And given that there is no _object_ attribute type, it makes me wonder how those 2 keys should be represented in memory via single key.

**Comment by clemensv** [comment]
@zihotki End-to-end tracing that includes the application is a real customer demand we are seeing at Microsoft, so this extension makes sense to us. traceparent and tracestate map to the exact corresponding fields in the W3C spec and from a wire-protocol perspective that's the spec that seems to be having the broadest support. If you don't like the name and want for that to be called "Open Tracing", I don't expect much opposition to a name change. However, I don't think we should litigate the tracing wars in this forum. If you think that some other tracing standard or framework needs support for its native construct, propose another extension. We specifically pushed for this to be an extension because it was clear from the outset that tracing is an area where everyone has their own favorite framework.
