### ISSUE TITLE
HTTP Binary spec: possibility of dropping attributes

### ISSUE THREAD

**Issue by evankanderson** [cloudevents/spec#498]
If you receive an event over HTTP Binary with an unknown extension attribute which has special header mapping rules, it will be dropped.

Currently, we have [Distributed Tracing](https://github.com/cloudevents/spec/blob/master/extensions/distributed-tracing.md) which defines a mapping from the tracing headers to CE attributes and vice-versa.

Imagine a new extension attribute which defines a similar mapping, and a client built before the extension attribute was known or defined. When receiving the attribute over HTTP Binary mode, the attribute will be dropped because the corresponding HTTP header does not begin with the magic string `CE-` (case insensitive).

Depending on the attribute, this data loss might substantially change the processing of the event. As a possibly-bad-idea, imagine a `processby` attribute which maps to the HTTP `If-Unmodified-Since`. If this header were stripped by middleware by accident, it might cause a event to be applied at the destination even if it should not be.

```
[client] --(HTTP)--> [middleware] --(AMQP)--> [processor]
```

**Comment by evankanderson** [comment]
Possible solution: define a `CloudEvents-Mapped` HTTP header (similar to the [HTTP `Connection`](https://tools.ietf.org/html/rfc7230#section-6.1) header.

Proposed syntax (using [ABNF from RFC7230](https://tools.ietf.org/html/rfc7230#appendix-B))

```
CloudEvents-Mapped = 1*map-option
map-option         = token *1( "/" token )
```

Where the example above would be written as "If-Unmodified-Since/processby"

**Comment by clemensv** [comment]
If there's a mapping, that mapping goes both ways - from and to the transport. 

For HTTP, a CloudEvents-aware intermediary will pick up the trace headers if they have been originating from the sender, but also if they have been injected or modified by a proxy. Being able to do so is a feature of HTTP. For tracing specifically, mapping to the standardized transport header fields is a feature.

If an extension wants to ensure that such headers flow end-to-end, it should mandate both mapping to the transport which makes them visible to standard infrastructure and then also carry them as regular attributes.

I don't think we need this complication since it is within the powers of each extension spec to do the right thing.

**Comment by duglin** [comment]
I can't decide if this is a real problem or not.  If we're really talking about middleware and what it passes on, or not, then in binary mode I wonder whether the middleware will have the same concerns for all extension HTTP headers.  Meaning, the event could have other HTTP headers, not part of CE, that could impact the processing of the event (http body). And so it feels a little to me like a well behaving middleware should pretty much pass along everything since it has no idea what's going to be needed downstream. 

Net: I guess what I'm wondering is whether or not this is a CE issue or just a generic middleware issue and we don't need to solve it because however the middleware deals with other unknown http headers is how it'll deal with CE's.

**Comment by deissnerk** [comment]
@duglin I think it is CE specific, as it occurs, whenever a CE is forwarded with a different transport binding. 
I wonder, if in addition to what @evankanderson mentioned in the issue, there could also be the opposite problem of accidentally picking up an additional attribute, that was not intended to be a CE attribute but matches with an extension.
Perhaps what @clemensv proposes is a simple solution: extensions should be required to have a "CE-" representation and could optionally specify another representation to expose the attribute to existing and not CE-aware infrastructure. This duplication of the attribute would usually not hurt more than an additional mapping attribute. Of course, for an attribute with a 1KB value, it wouldn't be ideal, but we are discouraging the use of long values anyways. 😬

**Comment by duglin** [comment]
@deissnerk but what about other non-CE http headers that are part of the event? Wouldn't those need to be forwarded on too? For example, the tracing header... if someone sent an event (w/o CE) what would the middleware do today? If the middlware ignores it, then we're no worse off when CE is introduced - there is no guarantee that extensions are used by receivers. But if it forwards it then we didn't need to worry about it. Just seems like a generic problem/solution to me that isn't CE specific.

In some respects, I kind of wonder if the tracing extension makes sense as a CE extension at all. Basically, all we did is point to an existing spec and don't really provide any additional guidance or usage pattern.  The same net effect as if the extension doc were not written at all,but someone wanted to use tracing. I don't think they need our md file to make it happen, or to get interop.  Maybe all it does is provide a way to say "if you want some tracing, then use this spec over here" - which we can get by having a set of "recommended other specs to consider so we don't have to reinvent things in CE". Which is kind of all we're doing now - just with more text - isn't it?

**Comment by clemensv** [comment]
The tracing extension as it stands allows for an event publisher to either act as the origin of a trace context or to propagate the context of whatever the occurrence was. 

If the event gets forwarded via HTTP, the trace context is mapped to the HTTP header where it can now be picked up by HTTP infrastructure that is aware of the W3C trace context spec and logged appropriately. 

When the event gets dispatched back from the HTTP context to code that understands CloudEvents _and_ the extension, the context gets propagated into the CloudEvents context. If the extension is not there, the context info isn't propagated back into the CloudEvents context.

If the latter is a problem because, for instance, the original trace context is required end-to-end wherever the event ends up being routed to, carrying the same info twice will help. With that you get trace context that is propagated through the transport infra if you want it, but you can also get a trace context that is purely at the app level.

Either choice is a concern of the tracing spec, not of CloudEvents framework or the HTTP binding per-se.

**Comment by evankanderson** [comment]
Tracing is one good example of this; our `datacontenttype` attribute is another example.

I'm particularly concerned about future extensions where a sender may know about the extension but middleware (e.g. an HTTP-to-AMQP bridge) does not know about the extension.

**Comment by clemensv** [comment]
I believe #505 is a good solution.
