### ISSUE TITLE
Support for AMQP 0-9-1?

### ISSUE THREAD

**Issue by jimeh** [cloudevents/spec#546]
Are there any plans for adding a document about how to transport CloudEvents over the wire with [AMQP 0-9-1](https://www.rabbitmq.com/protocol.html)?

The AMQP Protocol Binding document is for the AMQP 1.0 protocol, and in my experience most systems still use AMQP 0-9-1, and are often unlikely to switch to AMQP 1.0 anytime soon as it's technically a completely different protocol.

**Comment by duglin** [comment]
@clemensv any comment on this one?

**Comment by clemensv** [comment]
AMQP 0.9.1 is effectively the proprietary protocol of RabbitMQ by now since that is the only major broker that has held on to this draft version of AMQP that has otherwise been abandoned by the rest of the AMQP implementer community.

Apache Qpid and Apache ActiveMQ have moved on to AMQP 1.0 and so have most other commercial products. RabbitMQ has an AMQP 1.0 plugin that we have also used in our interop demo for various conferences, which means that there is a clear path for RabbitMQ users.

If someone wants to propose a spec for 0.9.x that will certainly be welcome for linking from the [proprietary-specs](https://github.com/cloudevents/spec/blob/master/proprietary-specs.md) folder, but AMQP 0.9.1 doesn't meet our criteria for inclusion as a top-level spec because it is an expired draft of a protocol for which we already have a formal binding. 

Walking away from the majority consensus of a standardization effort has consequences. We would not want anyone to include CloudEvents 0.1 as the reference version inside another standard.

**Comment by duglin** [comment]
I'm going to close this as I think @clemensv addressed the question/concern.  Thanks @clemensv 

@jimeh if you think we need to re-open it let me know

**Comment by jimeh** [comment]
@duglin, @clemensv, thanks for help and explanation :)

If you're happy to accept a proprietary spec for AMQP 0-9-1, I'd expect that's the path my client will choose to take to acheive CloudEvents spec compliance. Their queuing systems all use RabbitMQ with consumers written in Ruby and Java. And for Ruby at least, there doesn't seem to be any RabbitMQ-compatible client libraries that supports AMQP 1.0.

**Comment by michaelklishin** [comment]
@jimeh RabbitMQ AMQP 1.0 client integration tests use a .NET AMQP 1.0 client. We haven't tried any Ruby ones but if you see incompatibilities, please share them on the RabbitMQ mailing list so that they can be investigated. Thanks.

**Comment by rcollina** [comment]
@jimeh I for one could really use a spec for 0-9-1/RabbitMQ.
I think it would be hugely beneficial for the rmq userbase.

**Comment by jimeh** [comment]
@michaelklishin it's less about incompatabilities, and more that there are no RabbitMQ client libraries for Ruby that support AMQP 1.0 as far as I know, or that I can find with some quick Googling.

Both the [`bunny`](https://github.com/ruby-amqp/bunny) and [`amqp`](https://github.com/ruby-amqp/amqp) gems use AMQP 0-9-1.
