### ISSUE TITLE
(Batch) events error handling

### ISSUE THREAD

**Issue by xpepermint** [cloudevents/spec#566]
This spec says that error handling is out of scope. I prefer opinionated standards and I think the error handling part should be included.

More on this here: https://github.com/cloudevents/sdk-javascript/issues/46

**Comment by duglin** [comment]
I believe this is in reference to: https://github.com/cloudevents/spec/blob/master/primer.md#protocol-error-handling

**Comment by duglin** [comment]
Anyone think we should standardize this? 

My 2 cents... if CE was not in the picture the receiver would already have a defined way it returns errors - especially in the CE binary case, CE attributes are just extra HTTP headers and shouldn't impact what on the wire in either direction. As for CE structured, I think the same general rules apply.

Will ask on this week's call if we should close.

**Comment by erikerikson** [comment]
Hello @xpepermint.  This is a tough nut because although it makes sense to specify error handling in a synchronous HTTP call (as you discussed), the "proper" way to handle a error producing event received via an enterprise bus/message queue is a lot less clear and standardized.  Some like to reject non-compliant messages before they ever enter the queue and a non-compliant message is tantamount to a security or process breach while others are happy to give up that tight control of inflow (particularly in large organizations where the politics are prohibitive) and as such rely on constructs like a poison-pill queue and the like.

Some of the in-scope use cases are multi-organizational and while some of those are going to be explicit and close collaborations others are likely to be between non-communicating parties so that no influence can be had on the policies of the producers.  I can imagine myself responding to that by noting that it is all the better to have a standard but in order to have one we would have to define what is correct in the scope of and across all supported protocols (and really all non-supported protocols) and chains thereof.  I don't expect that to be a tractable problem of for the entire industry to agree to let us specify correct for them.  How do we correctly transitively propagate error handling transitively through some unknown number of protocols used by some unknown number of intermediaries?

Sorry for a rant'ish response but if you can point out what I missing from my thoughts expressed here or how I am being ignorant, I'd deeply appreciate the feedback so I can get smarter

Unfortunately as much as I'd like the world to be simpler, I think we should close this.

**Comment by duglin** [comment]
Closing but we can re-open if we get more comments/details.
