### ISSUE TITLE
Proposal for a new Protobuf spec

### ISSUE THREAD

**Issue by drtriumph** [cloudevents/spec#576]
In response to #504 I'd like to start discussion on a new spec for Protobuf (I'm not sure this is the right place but it seems as good as any)

Here's my initial pass for comment

```protobuf
syntax = "proto3";

package io.cloudevents.v1;

import "google/protobuf/any.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

message CloudEvent{
  // Required Fields
  string id = 1;
  string source = 2;
  string spec_version = 3 [json_name="specversion"];
  string type = 4;

  // Optional Fields
  string data_content_type = 5 [json_name="datacontenttype"];
  string data_schema = 6 [json_name="dataschema"];
  string subject = 7;
  google.protobuf.Timestamp time = 8;
  google.protobuf.Value data = 9;
  bytes data_binary = 10 [json_name="data_base64"];
  google.protobuf.Any data_proto = 11 [json_name="iocloudeventsprotodata"];
  google.protobuf.Struct extention_context = 12
    [json_name="iocloudeventsprotoextentioncontext"];
}
```

### Pros

- Serializes strictly to the JSON spec using default protobuf tooling
- Uses google.protobuf well-known types to store anything you could in a JSON event
- Strictly defines types for all required and optional attributes not data / extensions
- Handles time and base64 format conversion

### Cons

- Silently drops extension context attributes of a JSON event when serialized into a protobuf using standard tooling
- Is somewhat clumsy / unidiomatic in most languages to add and extract data attributes as they don't have specific or consistent types

If this is generally a good direction I'm happy to turn this into a PR for further comment.

## Example

Marshaling to and from a JSON event in Go yields:

Input:
```json
{
    "id" : "C234-1234-1234",
    "source" : "/mycontext",
    "specversion" : "1.0",
    "type" : "com.example.someevent",
    "datacontenttype" : "application/json",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "data" : {
        "appinfoA" : "abc",
        "appinfoB" : 123,
        "appinfoC" : true
    }
}
```

Output:
```json
{
    "id": "C234-1234-1234",
    "source": "/mycontext",
    "specversion": "1.0",
    "type": "com.example.someevent",
    "datacontenttype": "application/json",
    "time": "2018-04-05T17:31:00Z",
    "data": {
        "appinfoA": "abc",
        "appinfoB": 123,
        "appinfoC": true
    }
}
```

Go `%+v` output:
```
id:"C234-1234-1234" source:"/mycontext" spec_version:"1.0" type:"com.example.someevent" data_content_type:"application/json" time:<seconds:1522949460 > data:<struct_value:<fields:<key:"appinfoA" value:<string_value:"abc" > > fields:<key:"appinfoB" value:<number_value:123 > > fields:<key:"appinfoC" value:<bool_value:true > > > >
```

**Comment by dan-j** [comment]
Glad someone else has brought this up, I’ve been thinking about this today too.

Still fairly new to the project but having poked around the Go SDK for the past week or so, I have a few comments/suggestions.

First off, I think it would be better to not map to the JSON spec. 

I’m not sure how the following translates for other programming languages but I’m fairly sure this is language agnostic. The Go SDK treats events as either “structured” or “binary” encoded. What you’ve proposed is structured because deserialising the raw data gives you the full event (i.e. the JSON spec). 

Instead, I think it would be better to treat protobuf data as “binary encoded”, which means your `.proto` file will probably have separate fields for `attributes`, `extensions`, `data` and `data_base64`. 

When it comes to `data`, unless it’s a simple/scalar value, it would be better for producers/consumers to use `data_base64` as an embedded protobuf. Clients consuming this data would then have to identify which protobuf to parse the data as by using the `type` field. In the Go SDK this is a non-issue because `event.Data` comes as a `[]byte` anyway.

Thoughts?

**Comment by drtriumph** [comment]
I'm not sure what you're proposing - are you suggesting that a protobuf integration is simply marshaling a proto into bytes and using another binding e.g. HTTP or Kafka for the transport?

My goal is to essentially allow passing Cloud Events natively via gRPC services, e.g.

```protobuf
service SomeService {
    rpc Stream(stream io.cloudevents.v1.Event) returns (google.protobuf.Empty) {}
    rpc Listen(ListenRequest) returns (stream io.cloudevents.v1.Event) {}
}
```

I'll try and have a play with the Go SDK to get a better idea about what you're suggesting. I think this allows both structured and unstructured data to pass through via either the `data` or `data_base64` fields.

**Comment by dan-j** [comment]
No I’m not suggesting using another binding, and your service definition is the correct approach.

What I‘m commenting on is the actual structure of the protobuf. 

You have tried to structure the protobuf in the matching format to the JSON structure. This approach is called “structured encoding”. You’ve highlighted the problems with this approach in your “cons” list.

What I’m suggesting is to define the protobuf format so that it can carry all the information required to fulfil the specification. Then when the gRPC binding processes the event (either as a receiver or a sender), it must process the event to/from the protobuf format. This approach is called “binary encoding”.

Take a look at how the HTTP binding in the Go SDK works. HTTP can operate in both structured and binary encoding. Structured mode is where the full event is sent as a JSON object as the request body, whereas binary mode puts the `data` of the event in the request body and the other cloudevent attributes and extensions are stored in the Request Headers. Notice that in binary mode the binding must know the internals of how the event is structured specific to that protocol in order to process it.

Hope that helps?

**Comment by drtriumph** [comment]
I still think I might be missing something. My approach allows the transmission of binary data through the `data_binary` field which is defined as a `bytes` protobuf type i.e. I think it allows both "structured encoding" and "binary encoding".

For example I could wrap the example event from above in another event and have (this time output in text proto format):

```
id: "C234-1234-1235"
source: "/mycontext"
spec_version: "1.0"
type: "com.example.somewrapperevent"
data_binary: "\n\016C234-1234-1234\022\n/mycontext\032\0031.0\"\025com.example.someevent*\020application/jsonB\006\010\324\272\231\326\005J<*:\n\021\n\010appinfoA\022\005\032\003abc\n\025\n\010appinfoB\022\t\021\000\000\000\000\000\300^@\n\016\n\010appinfoC\022\002 \001"
```

I consider the ability for the standard tooling to be able to transcode from the JSON format in the naive case an additional merit of my approach but not a core tenet - it is possible to store any Cloud Event in its entirety within this definition but it would take a small amount of translation code to cover the corner cases around the extension contexts.

I imagine if anyone were to use this as a primary transport mechanism they would make heavy use of either the `data_binary` or `data_proto` fields rather than transforming their payload to and from a `github.com/golang/protobuf/ptypes/struct.Value`.

Do you have a specific suggestion of how the proto definition should look or how to update the one I proposed above?

p.s. reading the output above lead me to edit the original proposal and change `data_base64` to `data_binary` with a json rename to reflect the automagic transcoding the proto library does to the bytes type to base 64

**Comment by drtriumph** [comment]
Aside: the only difference between `data_binary` and `data_proto` is that the latter also includes a `type_url` which helps with unmarshaling. Here's the same wrapped event using the `data_proto` field instead:

```
id: "C234-1234-1235"
source: "/mywrappedcontext"
spec_version: "1.0"
type: "com.example.somewrapperevent"
data_proto: <
  type_url: "type.googleapis.com/io.cloudevents.v1.Event"
  value: "\n\016C234-1234-1234\022\n/mycontext\032\0031.0\"\025com.example.someevent*\020application/jsonB\006\010\324\272\231\326\005J<*:\n\021\n\010appinfoA\022\005\032\003abc\n\025\n\010appinfoB\022\t\021\000\000\000\000\000\300^@\n\016\n\010appinfoC\022\002 \001"
>
```

**Comment by duglin** [comment]
ping @evankanderson

**Comment by drtriumph** [comment]
🏏 🏏 🏏

**Comment by evankanderson** [comment]
... getting back to this from a conversation somewhere else, I'd echo a few points of @dan-j 👍 

1. I'd consider the automatic JSON -> Proto conversion to be an attractive nuisance here, and instead focus on the core data model of CloudEvents:
   * An unbounded collection of typed attributes, with a few well-defined ones.
   * A data payload which is a collection of bytes.
2. Once a representation for a single CloudEvent is defined for protocol buffers, something like your service definition would be a reasonable one, though you may also want to define unary send and bidirectional request/response and streaming RPCs.

Note that proto tag mapping makes it difficult to handle the attributes, as there is no authority or central registry to assign tag numbers, and an implementation attempting to transcribe a received message with an unknown tag number to some other format will be SOL because proto does not encode the schema alongside the message.

On the bright side, while JSON format has difficulties representing a raw bytestream, proto can encode the payload as a `byte` field easily.

My suggestion would be something like the following:

```proto
message Value {
  oneof value {
    bool bool_value = 1;
    int64 int_value = 2;
    string string_value = 3;  // Use this for URI and URI-reference
    byte byte_value = 4;
    google.protobuf.Timestamp time_value = 5;
  }
}
message CloudEvent {
  // These attributes with tags 1-4 are required by the spec
  string id = 1;
  string type = 2;
  string source = 3;
  string spec_version = 4;

  // All other attributes should be encoded in "attributes", whether
  // they are defined in the core spec or an extension.
  map<string, Value> attributes = 5;

  // The event payload data. Note that it is valid to store an encoded protocol buffer
  // in the bytes data if desired.
  bytes data = 6;
}
```

My reasoning for encoding all non-required attributes in the map is as follows:

> The main challenge in the protocol encoding is handling the upgrade case where one speaker promotes a field from the attributes map to a top-level tag, since proto binary encoding does not serialize much tag metadata (only the type which is needed for length calculations). In this scheme, I've opted to direct all the optional attributes into the map to try to prevent users from stumbling into the field upgrade issue.

**Comment by JemDay** [comment]
@drtriumph - I feel really dumb now, I didn't look at the issue list before proposing a PR on this subject.

Please take a look at PR #626, it's essentially following the model described above.

**Comment by drtriumph** [comment]
@JemDay No worries - I'm just happy this is getting some traction. I'll try and take a look tomorrow

**Comment by JemDay** [comment]
@drtriumph - Chris, I think the proposal is close to acceptance, if you're able to take a look that would be great (PR #626).

**Comment by drtriumph** [comment]
I took a quick look earlier in the week and you're right that it looks like the recommendation above. I think the choice of `oneof` is fiddly and not particularly intuitive at lease in Go where I'm most familiar, and I'm not super happy with the ongoing maintainability (i.e. it needs updating if there's a new type - e.g. int64) but I'm happy if other people agree and we can get some consensus.

To be fair using `google.protobuf.Struct` and `google.protobuf.Value` is awkward too, but it does allow arbitrary nesting of data within the `data` field in a type-safe way without having to define your own proto - e.g. for transcoding JSON events.

I'll miss the ~80% compatibility using regular tooling to transcode to the JSON spec and back, but I will concede that if it's not 100% then it will cause issues somewhere.

Implementation beats oration - closing out this bug in favour of your PR, thank you
