### ISSUE TITLE
Consider GraphQL for Discovery/Subscription APIs

### ISSUE THREAD

**Issue by mikehelmick** [cloudevents/spec#596]
# Overview

As part of the design exercise for the discovery and subscription APIs,  it was suggested that we consider GraphQL instead of REST.

To start the conversation, I've put together a candidate design for what a GraphQL API would look like.

You can see it in action here: [discovery.in-the-cloud.dev](https://discovery.in-the-cloud.dev/
)

There this provides for essentially 3 entry points for discover in the RootQueryType

- `providers` - Search for human readable providers
- `types` - search for know events by ce-type
- `search` - open search against providers and types

This leads to other queries that narrow in on information to actually get the information needed to create a subscription.

- `producer(provider:, type: )`

# Reasons to choose GraphQL

- Flexibility for representing the relationships we have
  - provider <-> type
  - {provider, type} -> producer
- allows for easy future expansion if we wanted to introduce `source` discovery (ce-source)
- Sever libraries available in many languages: https://graphql.org/code/
  - Client libraries available: https://graphql.org/code/#graphql-clients

# Discovery Example

1. What providers to I have?

```GraphQL
{
  providers{
    name
  }
}
```

which produces the results 

```json
{
  "data": {
    "providers": [
      {
        "name": "Cloud Storage"
      },
      {
        "name": "Cloud SQL Database"
      },
      {
        "name": "IOT Broker"
      },
      {
        "name": "GitHub"
      },
      {
        "name": "Other Cloud Storage"
      },
      {
        "name": "Cloud Pub/Sub System"
      }
    ]
  }
}
```

2. -or- perhaps I want to also see the event types available, and also narrow the providers down to things with "storage" in the name

```graphql
{
  providers(matching: "storage") {
    name
    description
    types {
      name
    }
  }
}
```

Which would produce the results of

```json
{
  "data": {
    "providers": [
      {
        "description": "Cloud Blob Storage",
        "name": "Cloud Storage",
        "types": [
          {
            "name": "com.storage.object.create"
          },
          {
            "name": "com.storage.object.delete"
          }
        ]
      },
      {
        "description": "A differe cloud blob storage",
        "name": "Other Cloud Storage",
        "types": [
          {
            "name": "com.storage.object.create"
          },
          {
            "name": "com.storage.object.delete"
          }
        ]
      }
    ]
  }
}
```

3. Given a `provider` and an event `type`, it is possible to narrow down into the details needed to create a subscription.

```graphql
{
  producer(provider: "Cloud Storage", type: "com.storage.object.create") {
    dataSchema
    dataContentType
    subscriptionConfig {
      name
    }
    subscriptionEndpoint
    protocols
  }
}
```

which produces the results of 

```json
{
  "data": {
    "producer": [
      {
        "dataContentType": "application/json",
        "dataSchema": "https://schemas.in-the-cloud.dev/download/com.storage.object.create.json",
        "protocols": [
          "http"
        ],
        "subscriptionConfig": [
          {
            "name": "path"
          }
        ],
        "subscriptionEndpoint": "https://subscribe.events.broker/com.storage.object.create?provider=Cloud Storage"
      }
    ]
  }
}
```

**Comment by Thoemmeli** [comment]
@mikehelmick Thanks a lot for providing the sample. 

### Reasoning
While I just started to learn the details of GraphQL, I found the following reasoning statements inspiring:

[GitHub](https://developer.github.com/v4/#why-github-is-using-graphql)
> GitHub chose GraphQL for our API v4 because it offers significantly more flexibility for our integrators. The ability to define precisely the data you want—and only the data you want—is a powerful advantage over the REST API v3 endpoints. GraphQL lets you replace multiple REST requests with a single call to fetch the data you specify.
> 
> For more details about why GitHub has moved to GraphQL, see the original announcement blog post.

[GitLab](https://docs.gitlab.com/ee/api/#road-to-graphql)
> GraphQL has a number of benefits:
> 
> 1. We avoid having to maintain two different APIs.
> 1. Callers of the API can request only what they need.
> 1. It is versioned by default.

### Attribute Casing
Probably in GraphQL it is very common to use camelCase (e.g. for `"dataContentType"`) for query attributes. For consistency with the CloudEvents [Attribute Naming Convention](https://github.com/cloudevents/spec/blob/master/spec.md#attribute-naming-convention), it might be better to use `"datacontenttype"`.

**Comment by clemensv** [comment]
It's reasonable to add GraphQL queryability as a layer or optional feature, but clients should still be able to do simple requests simply and with a simple URI path expression to access all items of a collection or a single object. 

Please keep in mind that these mechanisms must work down to constrained devices where develeopers don't have the liberty to import a ton of library dependencies.

**Comment by duglin** [comment]
I like the idea of having the base be a simple REST/URL based mechanism, and then allowing for other query languages on top as options. In the end, I think we need to support clients that do not want to, or can not, leverage additional tooling just to talk to implementations of our specs. Personally, I avoid tooling and try to boil most things down to simple curl cmds (w/o bodies when possible).

**Comment by Thoemmeli** [comment]
Basically I do agree with @clemensv and @duglin to have a REST based API since it is still the usual API mechanism.

To call a REST API with curl commands without a body seems to be simple in the first place, but when you look at the variety of calls, it gets more complicated and I see this as a trade-off compared to GraphQL. Additionally the return values are JSON objects as proposed in the [discovery document](https://github.com/cloudevents/spec/blob/master/discovery.md). That means that either way you need to deal with http body and with parsing it anyhow.

Here are the currently proposed REST Path for [discovery](https://github.com/cloudevents/spec/blob/master/discovery.md):

> /providers?matching=[search term]
> /providers/{name}
> /providers/{name}/types
> /types?matching=[search term]
> /types/{name}
> /types/{name}/providers
> /producer/{provider.name}/{type.name}

We are ending with 3 different entry points with potentially different operations each (GET, PUT, DELETE, POST). Defining and remembering what is valid as `[search term]` is difficult. Does OpenAPI even give you support for that? I don't know.<br>Someone might argue that this is not complicated, because we are so used to do it like that. Personally I struggled a lot when defining an interface whether to put something into the PUT or POST verb.

In [GraphQL](https://graphql.org/) you would have **just one single interface** with more flexibility. I found this very attractive, streamlined and clear. The valid query paramers can be queried directly in the interface with [introspection](https://graphql.org/learn/introspection/). Every GraphQL interface has a [schema and a type system](https://graphql.org/learn/schema/) behind. The schema support in REST was added by [Swagger](https://swagger.io/), [OpenAPI](https://www.openapis.org/) or [RAML](https://raml.org/) later.<br>
Chaning of objects in GraphQL can be done with explicitly defined [mutations](https://graphql.org/learn/queries/#mutations).

```GraphQL
mutation CreateReviewForEpisode($ep: Episode!, $review: ReviewInput!) {
  createReview(episode: $ep, review: $review) {
    stars
    commentary
  }
}
```

As a trade-off for GraphQL the complexity has been moved from the URL to the body of the request though.

We should give the consumers of CloudEvents the choice which technique they prefer, but we should offer GraphQL as an alternative. I am not a GraphQL specialist, but I see a lot of potential. [As stated earlier](https://github.com/cloudevents/spec/issues/596#issuecomment-605623081), I am sure there is a reason why GitHub and GitLab are moving into the direction of GraphQL. 

Someone with experience in GraphQL, which I don't have, should guide us in that new and promising field of APIs.

**Comment by duglin** [comment]
This was discussed on the 5/7 call and we decided to start with REST but then to revisit this issue prior to v1.0 of the new specs.

**Comment by duglin** [comment]
I'd like to propose that we close this - not to necessarily kill the idea but rather to clean-up our backlog. If someone wants to propose this again then they can open a PR, but the issue by itself has probably gone as far as it can go. Plus, no one has mentioned a desire for this in over a year.

**Comment by duglin** [comment]
Done - created "backlog" label. Let me know if you think other issues should get that label too. I'll check the recently closed ones
