### ISSUE TITLE
Message structure related question

### ISSUE THREAD

**Issue by VitalySh** [cloudevents/spec#601]
Hello,

Was there any obvious reason of flattening the object instead of using a separate blocks for metadata (map<string>string) and payload(any type/encoding) ?

It is actually not very clear how extendable and flexible the structure is

Looking forward to your soonest reply and thanks in advance

**Comment by duglin** [comment]
@VitalySh I would read the 2 sections in the primer starting at https://github.com/cloudevents/spec/blob/master/primer.md#cloudevent-attribute-extensions

While that focuses on "extensions" it'll give some insight into some of the discussions and decisions we made around why additional layers/groupings would add unnecessarily complexity.

However, I'm not sure I understand your question since in "structured" mode we do have two sections - one for the payload (under `data`) and then everything else is metadata.

**Comment by VitalySh** [comment]
@duglin thanks for the reply and apologies for being not very clear about the question
I just wonder why we are not using lower level bindings such as payload as bytes/base64 and context as a flat map all the way around. This way we would not be bound to the implementing particular extensions and it would be easier to manage integrations ( extensions are something within a standard, although it could be just p2p integration where it should not be that broad )

**Comment by n3wscott** [comment]
Howdy @VitalySh I was wondering if this question was coming from a particular integration? And if so which, and for which language? I don't quite follow your question still. You seem to be suggesting what the spec says you can do.

**Comment by duglin** [comment]
Circling back to this.... if I'm following, you're asking why the body isn't something like:
```
{
  "metadata": {
    ...ce attributes...
  },
  "data": {
    ...event payload...
  }
}
```
correct?
If so, to me this introduces 2 points of extension instead of just 1. People could add more attributes in "metadata" AND as a sibling to "metadata". Then the spec would need to define what each one means and what to do if the same attribute (with different values) means at each spot.  Net: the wrapper doesn't really provide any value but could introduce inconsistent and hurt interop if people choose to put extensions in both places.

**Comment by duglin** [comment]
@VitalySh we discussed this on today's call and aside from the comment above, there wasn't an interest in re-opening the "bucket" thread that we've had quite a few times in the past.
