### ISSUE TITLE
Re-org the repo

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#633]
Per my action items, what do people think of this layout:

```
CONTRIBUTING.md
GOVERNANCE.md
LICENSE
Makefile
OWNERS
README.md

artwork/
community/

cloudevents/
  adapters/
  adapters.md
  documented-extensions.md
  cloudevents.md   # renamed from 'spec.md'
  extensions/
  formats/
    avro-format.md
    json-format.md
  sdks/
    sdk.md        # renamed from "sdk.md"
  primer.md
  protocols/
    amqp-protocol-binding.md
    http-protocol-binding.md
    http-webhook.md
    kafka-protocol-binding.md
    mqtt-protocol-binding.md
    nats-protocol-binding.md
  proprietary-specs.md
  roadmap.md
  source-event-action.png     # move to '/artwork' ?
  spec.avsc
  spec.json

discovery/
  discovery.md

share/

subscriptions/                      
  subscriptions-api-openapi.yaml    # just 'subscriptions-openapi.md' ?
  subscriptions-api.md              # just 'subscriptions.md' ?
  
tools/
```

**Comment by deissnerk** [comment]
I wonder, if subscriptions and discovery should be in separate directories. We started with separate working groups, but they are closely related, and if we write a primer for them, I would opt for a common primer for both topics.

**Comment by grant** [comment]
It seems like the goals are reducing the number of top-level files?

Thoughts:
- Use `.github/` folder for files like CONTRIBUTING.
- Don't have a folder `cloudevents/`. We're already in the cloudevents org, spec repo. Rather flatten the folder so we can directly see the list of files.
- Folders like `artwork` seem like they should be a link from the README to source files rather than a directory in the spec.
- Other suggestions above look like an improvement 👍

**Comment by duglin** [comment]
> I wonder, if subscriptions and discovery should be in separate directories.

I'd be ok with merging them... have any suggestion for a name?

> It seems like the goals are reducing the number of top-level files?

That's a nice side-benefit, but it's actually more about grouping things that are related so they're easier to find. At this point in time there doesn't seem to be much desire to create a new repo for the new specs, so until we do it seems like folders is a good way to do the grouping.

>    Use `.github/` folder for files like CONTRIBUTING.

I can't seem to find any good docs on what files can/should go in there aside from things like issue templates.  What happens when CONTRIBUTING is in there? I've been assuming people who care about stuff like this are used to see things like CONTRIBUTING and LICENSE at the root of repos.

>    Don't have a folder `cloudevents/`. We're already in the cloudevents org, spec repo. Rather flatten the folder so we can directly see the list of files.

So even more top level files?

**Comment by grant** [comment]
Here are a couple links:
- https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors
- https://github.com/rhysd/dot-github/tree/master/.github

> So even more top level files?

I would suggest grouping files in top-level folders and leave things like `protocols/` and `formats/` at the top level. If it makes sense to verbally say "Cloud Events spec protocols" or "Cloud Events spec formats", then we can mirror the file structure that way with `cloudevents/spec` `protocols/`.

**Comment by JemDay** [comment]
Generally a +1, I like the approach of grouping the protocols and formats into their own folders.

Where we have associated schema files should those move into the `/formats` space or should there also be a 'schema' directory to hold them.

I'm thinking forward where we might define a gRPC protocol  spec which would also have an associated schema/idl

**Comment by tweing** [comment]
Basically I like grouping.

I would keep `spec.md` on the top level. I liked the `spec` part in the name.

Additional documents could go into a `docs` folder.

Schema files should be along with the md file (e.g. discovery schema in `discovery` folder, cloudevents schema where `spec.md` is).

Discovery and Subscription should be kept together because they are very closely related to each other. Maybe just in the `discovery` folder.

**Comment by duglin** [comment]
Closing since we already did a re-org
