### ISSUE TITLE
Add "initiator" field?

### ISSUE THREAD

**Issue by johanhaleby** [cloudevents/spec#638]
Hi, 

I've tried searching both the issues and the mailing list but I couldn't find any discussions around this so I'll give it a shot here, sorry in advanced if I've missed something. 

Essentially I'm interested in your thoughts around adding a field to the spec that represents the "initiator" of the event? In my experience this is often interesting. For example:

```json
{
    "specversion" : "1.0",
    "type" : "com.github.pull.create",
    "source" : "https://github.com/cloudevents/spec/pull",
    "subject" : "123",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "datacontenttype" : "text/xml",
    "data" : "<much wow=\"xml\"/>"
}
```

Here the `source` and `subject` combined uniquely identifies a specific pull request. I'm looking for something similar for the "actor" (person or system) that initiated (created) the pull request that _caused_ this event to be published in the first place. Something like:

```json
{
    "specversion" : "1.0",
    "type" : "com.github.pull.create",
    "source" : "https://github.com/cloudevents/spec/pull",
    "subject" : "123",
    "initiator": "https://github.com/johanhaleby",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "datacontenttype" : "text/xml",
    "data" : "<much wow=\"xml\"/>"
}
```

Or would this be better represented as an extension or even inside the `data` attribute?

**Comment by savage-alex** [comment]
@johanhaleby is it not safest in the data object as it could contain sensitive / PID that you may want to encrypt for GDPR / sensitivity reasons? (I only say that as I have added in initiator into the data field)

**Comment by duglin** [comment]
@johanhaleby thanks for the issue. In the past the group has decided to stay away from things like "users" and authentication due to there not being a clear single way to describe or solve the problem. So, trying to get agreement across the entire community for what a "user" might mean will be a challenge We did talk about this on the call today though and it was suggested that if this information were to exist it would be better to appear in the event data itself, rather than as a CE property because it's not clear that it would be useful for routing purposes (at least not often enough to make it a first class property yet).  However, the group did think that if there was interest in this then someone could create a PR to define an extension (like the other ones we have) so that we could then gauge community interest in it.  But for now it was decided to close the issue - but feel free to open a PR to keep the idea around if you'd like to give it a go.
