### ISSUE TITLE
HTTP binding MUST content modes?

### ISSUE THREAD

**Issue by c-pius** [cloudevents/spec#643]
Hi folks,

in the documentation of the HTTP binding it states ([1.3. Content Modes](https://github.com/cloudevents/spec/blob/v1.0/http-protocol-binding.md#13-content-modes))
> Every compliant implementation SHOULD support the structured and binary modes.

In the section below ([1.4. Event Formats](https://github.com/cloudevents/spec/blob/v1.0/http-protocol-binding.md#14-event-formats)) it states
> All implementations of this specification MUST support the non-batching JSON event format,...

Does this second statement make structured content mode a logical MUST? I assume it is intended to say that: when supporting structured content mode, then JSON event format is a MUST?

Anyway, would it be sensible to have binary and structured mode as a MUST instead of a SHOULD?

Thanks!

**Comment by duglin** [comment]
I think your reading of section 1.4 is correct... I think the intent is that the MUST is within the scope of doing "structured".  We should probably clear that up.  Interested in a PR? :-)  If not, someone else will do it.

If I'm remembering correctly, I think we made it a SHOULD because it's a really good idea, but there are going to be times where an implementation just can't support anything but one (e.g. binary due to resource constraints) and so making it a MUST might prevent someone from adopting the spec.

Anyone else for either question?  @clemensv @n3wscott @deissnerk @cneijenhuis

**Comment by c-pius** [comment]
Sounds reasonable, thanks! About the PR... I would have to go through our corporate contributor enablement process so I guess that is a bit too much of overhead for this small contribution :)

**Comment by deissnerk** [comment]
@c-pius  @duglin  I think this issue can be closed, as my proposal of a clarification got merged.

**Comment by duglin** [comment]
great - thanks for circling back to this
