### ISSUE TITLE
[Discovery] Sources of truth in RESTful APIs

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/spec#679]
I just reread the spec with the aim to implement it and one thing really sticks out as weird to me. One of the RESTful principles is there is only 1 way to get an individual resource (or a collection). The issue I am seeing is in the `/types` request. You can get the full definition of a service in `/services` request, but also in a `/types` request. This violates the RESTful principles of single source of truth.

I understand the intent is for mapping types to services. I think we need to take a look at this and understand why `/types`  needs to return the full service definition, or if it can return a map of type to service id and let the `/services` endpoint be to source of truth for services.

**Comment by duglin** [comment]
I'm not sure REST requires only one way to get at metadata, but returning a list of URLs instead is possible. However, there are problems with that w.r.t. performance. Let's say we get back a list of 1000 services. Unless people can formulate some (potentially complex) query to `/services` that allows them to ask for that exact list of 1000, they'll need to call `/services/ID` 1000 times. That's not only going to be really slow compared to the `/types` stuff (which will, at worst, have several requests due to pagination), but people might run into rate-limiting issues.

We could allow for people to choose whether they want the deep list vs shallow list via a query parameter tho.

**Comment by n3wscott** [comment]
related to #684

**Comment by deissnerk** [comment]
I agree to @duglin in that I don't think REST requires that there is always only a single URL to retrieve a certain piece of information. In order to enable caching, clients usually should retrieve the same information using the same URL, though. Afaik it's a principle of REST that requests can be cached. 
I also agree to @n3wscott that we may need to take a look at why `/types` a list of full service definitions. There might still be some ambiguities in the data model.

@duglin In OData there is the `$expand` query parameter: 
[https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/using-select-expand-and-value](https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/using-select-expand-and-value)
[https://www.odata.org/getting-started/basic-tutorial/#expand](https://www.odata.org/getting-started/basic-tutorial/#expand)
