### ISSUE TITLE
Are null values for attributes permitted?

### ISSUE THREAD

**Issue by jskeet** [cloudevents/spec#702]
This is in the context of https://github.com/cloudevents/sdk-csharp/pull/68

I believe the spec should be clear about whether the concept of a "null" attribute value is supported - and then SDKs should be consistent in supporting or prohibiting it.

(My personal feeling is that they should be prohibited everywhere. Supporting them requires encoding that information in all transports etc, which is likely to be really tricky.)

**Comment by duglin** [comment]
Are there specific attributes you have in mind?  We tried to add text like "MUST be a non-empty string" and "If present, MUST be a non-empty URI" to deal with that.

**Comment by jskeet** [comment]
No specific attributes, no - and it's not about empty vs non-empty, either... it's about whether an attribute can be expressed with the absence of a value... a null reference in Java or C#, basically.

I'd argue that if the concept of expressing "this attribute is definitely not present" isn't supported by the overall spec, then SDKs for languages with the concept of null should either prohibit its use, or use it as an alternative way of removing an attribute. (I'd personally far prefer the former. If you want to remove an attribute from an in-language CloudEvent, call a suitable "remove" function. That leaves less room for ambiguity.)

**Comment by duglin** [comment]
This sounds a bit like an SDK issue, no?  I say this because CE itself doesn't have the concept of "removing an attribute"... there's nothing to remove an attribute from. It's either in the CE on the wire, or it's not. There's no state involved here. Or am I not following?

**Comment by jskeet** [comment]
It's an SDK issue, but one which should IMO be informed in the spec - or at least the SDK spec - so that it's handled consistently.

I agree that the CE itself doesn't have the concept of removing an attribute - but if we're explicitly about saying that it *also* doesn't have the concept of "an attribute with no value" then that makes it clearer that you shouldn't have a null value (which is effectively the absence of a meaningful value) in the SDK representation.

**Comment by deissnerk** [comment]
@jskeet I agree with you, and I remember having that discussion with @duglin and @clemensv on Slack quite a while ago, when preparing the demo for KubeCon EU 2019. I think we agreed that this should be clarified but forgot to follow-up. 😄 
I suppose it could be clarified in the section describing the [type system](https://github.com/cloudevents/spec/blob/master/spec.md#type-system).

**Comment by duglin** [comment]
I feel like I'm being slow here... can someone give an example of the type of thing they think the CE spec should say (that it doesn't already) to address this?  If this is strictly an SDK issue, to ensure we're consistent across SDKs, then I can grok that.

**Comment by jskeet** [comment]
> If so, then it must be in RFC 2064 format - - which null is not.

I suspect there was a typo in that RFC number (2064 is "Traffic Flow Measurement:  Meter MIB" - if that's as intended, I need to read it more carefully to see the relevance).

Note that `null` *is* a valid JSON value. So aside from anything else, explicitly stating that the value of an attribute in a JSON representation can't be null would be a start.

**Comment by duglin** [comment]
hehe - it should be 2046:  https://tools.ietf.org/html/rfc2046

**Comment by jskeet** [comment]
@duglin: It may be that it's fine to put it in the [SDK requirements](https://github.com/cloudevents/spec/blob/master/SDK.md). What I don't want is for each language to come up with their own rules. And ideally I'd like a justification for my current PR :)

But for the spec, we could add a note in the type system section along the lines of:

> Each context attribute must either be present in a CloudEvent with a value, or absent. The concept of "present, but without a value" is not supported.

(Far more wordsmithing required, but something along those lines.)

**Comment by jskeet** [comment]
@duglin: Thanks for the right RFC.

I see the JSON CloudEvent spec gives the type of JSON values that are permitted, so that already implicitly excludes `null` as a value for everything except `data`. I'd be interested to hear whether folks would consider these two events equivalent:

With data value of null:

```json
{
    "specversion" : "1.0",
    "type" : "com.example.someevent",
    "source" : "/mycontext",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "data": null
}
```

and without a data value...

```json
{
    "specversion" : "1.0",
    "type" : "com.example.someevent",
    "source" : "/mycontext",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z"
}
```

**Comment by duglin** [comment]
I wouldn't be against adding a sentence like that, but I'm still wondering why things like "MUST be a non-empty string" doesn't cover it. It seems to me that a non-empty string can never be represented in json as "null".

Scanning the spec, I think we may have a hole in the extensions section because I'm not sure we say that extensions can't be empty, like we do for individual CE defined attributes. So a PR to fix that seems like a good idea - and your sentence would cover that :-)

**Comment by duglin** [comment]
your `data` question is interesting.... what would/could a receiver do differently between those two cases?

**Comment by jskeet** [comment]
> your data question is interesting.... what would/could a receiver do differently between those two cases?

In terms of the "could" - it could be visible if an SDK exposes an operation of "list attributes present in the CloudEvent"... (if it considers "data" to be an attribute). This is precisely the kind of thing where I'd like to be consistent - although if it's *only* relevant for the `data` attribute, that's not as much of a problem.

I agree that "MUST be a non-empty string" is unambiguous here. We could either have a PR to only cover extensions, or make it global to *all* attributes (even though it's redundant for the existing context attributes) if that's simpler. Or again, this might end up only being needed in the SDK spec...

**Comment by duglin** [comment]
If we're talking about a situation where we're just displaying an incoming CE then I'm not sure why it would matter if data is missing or present but with null. Either way, there's no data.

Now, if the usecase is using an incoming CE to update something (like another CE) then I totally agree that missing may not be interpreted the same as null. And at that point I think it's an issue with the code/spec that defines that logic.

**Comment by deissnerk** [comment]
For reference, there is our conversation from last year on [Slack](https://cloud-native.slack.com/archives/C9DB5ABAA/p1559027434016200)

**Comment by duglin** [comment]
what a memory! :-)

Ignoring the extension issue, I'm still wondering if our current spec has an issue for our attributes given the "MUST NOT be empty" stuff.  We may have made a mistake if one of those attributes makes sense to be an empty string, and then we'd need to explain if null=="", but I'm assuming none of the existing attributes make sense as "".  And, in fact, the "if present" part of the text, or optional ones, basically covers it because if you want to do "" then you're forced to leave that optional attribute out of the serialization.  At least that's my reading of it.

**Comment by clemensv** [comment]
My stance on the issue remains the same as in the Slack thread. If you have a strongly typed object (or a database table) representing a CloudEvent, the absence of an optional attribute is expressed with "null". 

E.g. our [JSON support in .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#exclude-all-null-value-properties) has an override to treat "null" as "absent" and not serialize the fields out.

**Comment by JemDay** [comment]
As-per other comments in this thread, the way I [read the spec](https://github.com/cloudevents/spec/blob/master/spec.md#context-attributes) is that none of defined attributes allow for a nil/null value.

If we did support NULL values then I suspect the various transport bindings would need to understand how to convey such a value.

I'd vote for clarifying the specification to say that NULL values are not supported.

**Comment by deissnerk** [comment]
The defined attributes do not allow empty values. For optional values the spec states:
> If present, MUST be a non-empty[...]

I understand the case of an attribute not being present exactly as the null/nil value. That was also the context, when the issue popped up the first time in the Slack discussion I linked above. In a demo we had some attributes that were not always used and some clients rendered them as null. 

I propose to clarify for the CloudEvents type system that null/nil is equivalent to an attribute not being present. We would then also need a clarification for formats like JSON that distinguish these cases. Either `null` would be treated just like `undefined`, or it would be excluded completely.

**Comment by duglin** [comment]
As part of this discussion, I'd like to better understand the use cases where this even matters. For example, in the most common case of a CE being delivered to a Sink, would we expect the Sink to do something different between "not present" and "present but null" - even w/o clarifying text in the spec that says "treat them the same" ? What could a Sink do in either case other than treat it as if there's no data for that field?

I'm not pushing back on adding clarifying text, I'm just trying to understand which coding cases it would actually impact.

And, I'm asking because @n3wscott made a passing comment on one of our calls about being able to look at a CE and know if a certain field should be "removed" during the Sink's processing due to it being in the CE but "null". I didn't get a chance to ask for a clarification, but it sounded like Scott was thinking of using a CE as some sort of "diff" (or "update") format - meaning, using a CE to update a pre-existing CE in the Sink's persistence. In a case like this I can see why the two cases would need to be treated very differently. However, this is also a use case that I hadn't thought about using CE for and I think it would be good to know if this, or other cases like this, are even valid ones that we want to support.  As a side note, I would expect each CE to have a unique ID, so I'm not even sure how the Sink would know to correlate the incoming to an existing CE.

**Comment by duglin** [comment]
@n3wscott signed up to do a PR for this!

**Comment by n3wscott** [comment]
My take is the JSON wire format allows for `null` but this is equivalent to not set from the perspective of the CloudEvent object. 

> And, I'm asking because @n3wscott made a passing comment on one of our calls about being able to look at a CE and know if a certain field should be "removed" during the Sink's processing due to it being in the CE but "null". I didn't get a chance to ask for a clarification, but it sounded like Scott was thinking of using a CE as some sort of "diff" (or "update") format - meaning, using a CE to update a pre-existing CE in the Sink's persistence. 

I would not recommend using this as parts of the envelope. If you want to pass Diffs, then do it in the data would be my recommendation.
