### ISSUE TITLE
The difference among event source, event source type, event type, event ID is not explicit

### ISSUE THREAD

**Issue by cathyhongzhang** [cloudevents/spec#71]
Suppose the event comes from a AWS S3, what is the event source, event source type, event type, event Identifier?  From current definition, it is not very clear. 

Assigned to: @cathyhongzhang

**Comment by cathyhongzhang** [comment]
Can we discuss this in the meeting? I can own and resolve this issue. But I prefer to get other people's input on this first

**Comment by duglin** [comment]
ok I'll add it to the agenda

**Comment by deissnerk** [comment]
@duglin This partially covers what I meant by examples in in the discussion of #41 . 
@cathyhongzhang I think similar questions may occur for the other attributes. It might help a lot to create sample flows, where an event travels through a certain system, and for each hop it is described what the values for the attributes are. What do you think?

**Comment by duglin** [comment]
yep I agree.  We ran out of time last week, I'm hoping we can get to it today, but I wanted to ask a similar question about “event-type”, “event-type-version” and “schema-url” since it feels like there might be some overlap between these three things and I wonder if schema-url alone couldn't convey all of the info needed. And if not then we need a very clear definition so there's no confusion about when, and how, to populate them - otherwise we won't get the interop we need.

**Comment by cathyhongzhang** [comment]
Good idea. A sample flow will help to illustrate issues in our current definition, such as overlap or gap. We may find out that some new attributes, such as correlation-token, need to be defined to really get the interop we need.  I will try to draw the flow, show the boundary, and identify issues that need to be discussed. I can probably get this ready for discussion in the 2/22 meeting.

**Comment by cathyhongzhang** [comment]
Ok.
