### ISSUE TITLE
CloudEvents: How to describe that event was generated because of a previous event?

### ISSUE THREAD

**Issue by francardoso93** [cloudevents/spec#750]
Consider the following scenario for AMQP communication.

- App1 publishes message -> "type": "reportRequested"
- App2 is subscribed to "type": "reportRequested" and consumes this message; creates a PDF and publishes message -> "type": "reportPrinted"

App1 wants to subscribe to "reportPrinted", but only if this report is related to "App1", and not to "App3", "App4", "AppX"...

How would you do it? Should I use an existing CloudEvents attribute? Should I extend and use a new attribute?

**Comment by duglin** [comment]
For that particular case you'd need to look at some other data aside from a standard Cloud Event attributes since none of the CE attributes deal with correlation. So, either an extension attribute or something in the body of the 2nd event would need to convey the info you're looking for.

**Comment by slinkydeveloper** [comment]
We have a sequence extension, maybe this one helps? https://github.com/cloudevents/spec/blob/v1.0.1/extensions/sequence.md

**Comment by francardoso93** [comment]
@duglin that's what I thought. Unfortunately creating my own attribute for correlation could become a problem for pluggability with tools from different companies that use CloudEvents. Do you have plans to address this issue through standards or is it a design decision not to do it?

**Comment by francardoso93** [comment]
@slinkydeveloper this looks interesting. I wish there was examples to fully understand if it solves this scenario or not.

**Comment by duglin** [comment]
> @duglin that's what I thought. Unfortunately creating my own attribute for correlation could become a problem for pluggability with tools from different companies that use CloudEvents. Do you have plans to address this issue through standards or is it a design decision not to do it?

As of now, no - mainly for the reason you stated. There are so many different types of correlation that we weren't able to define it in a way that solved a majority of the usecases and promoted interoperabilty.

**Comment by lesterw1** [comment]
One of the techniques I've seen is to use a *correlationId* (usually a GUID value) which correlates the events corresponding to a particular transaction or event chain.  So App1 creates the first event and generates a new ```correlationId```. App2 consumes the event and generates a corresponding new event with a new ```id``` but crucially with the same ```correlationId```.

I've always thought that the CloudEvents specification should include ```corellationId``` as an optional top-level property to ensure consistent interoperability. Alternatively, it can be packaged inside the ```data:{ }```.

**Comment by duglin** [comment]
We had very long discussions about this in the past and it basically came down to one problem... what type of correlation would `correlationID` refer to?  child-of? caused-by? sibling-of? depends-on? And the list goes on. 

Since there isn't a single relationship that would cover all cases we decided that people could define their own for their needs. Meaning, people should define something like:
```
  "causedby": "ID-of-other-event"
```
where the ID can be the CE `id` value of the other event. Then whether this is a CE extension or in `data` is up to the business need.  This also allows for many different correlations to exist per CE - and we (the spec) don't get in the way.

**Comment by lesterw1** [comment]
Microsoft has done a good job defining ```correlationID```. It is usually the first event in the chain, but is generically defined as "_The correlation Id is shared among the events that belong to the same uber operation_".  I don't find it confusing at all. 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.monitor.models.eventdata.correlationid?view=azure-dotnet

**Comment by lesterw1** [comment]
This is a good read about correlationIDs. It really boils down to events related to a single action / transaction. In Microsoft Azure, this is an instance of an API call. The rule of thumb "_Assign the Correlation ID as soon as you can. And, if you find that you are passed a Correlation ID, use it._" works well.
https://blog.rapid7.com/2016/12/23/the-value-of-correlation-ids/

**Comment by duglin** [comment]
> It is defined as "The correlation Id is shared among the events that belong to the same uber operation". I don't find this confusing at all. 

I agree, that statement isn't confusing. However, the issue isn't whether we can come up with a definition that people can understand. It's whether we can some up with a single definition that applies in most (all?) cases. The one you describe seems valid, but to other people correlation might be more of a parent relationship (event B was caused by event A), not that they're both related to the same uber occurrence. And it's that lack of agreement that cause us to punt on the issue.

I've added this to the agenda for tomorrow's call.

**Comment by duglin** [comment]
We had a chat about this on our weekly call and the consensus was that we made the right decision by not trying to have a single definition since it wasn't clear which definition would be appropriate. However, the spec does allow for extensions and we have a list of [extension specs](https://github.com/cloudevents/spec/tree/master/extensions) in our repo. Any new attribute would probably need to start as an extension anyway, so if you (or anyone else) would like to open a PR to create an extension then that would be ok. And if it turns out that it becomes really popular then we'll consider adding it to the core spec.

**Comment by rcollina** [comment]
Hello,
If I may, I'd like to add my (humble) 2 cents on this matter.

We've been trying to adopt CloudEvents in the past months and I'm grateful there's a spec we can adhere to; besides the obvious technical benefits, there's also the valuable side-effect of having a third-party we can refer to and avoid "analysis in-fighting", as it were.

We've been introducing custom headers to add:
- a `conversation id`: spanning an entire chain of services interacting with each other via messaging
- a `correlation id`: it should correlate an async reply to the original command/request

My current predicament is that, when it comes to custom headers, as "end users" we're subject to making decisions without seeing the bigger picture (which your committee has) or consensus - mostly the latter, as I for one am lucky enough to work with very smart people.

There's a lot of prior art (for example, EIP by G. Hohpe, [link](https://www.enterpriseintegrationpatterns.com/ramblings/09_correlation.html)), which more or less describes what we intuitively need in our day-to-day to reconstruct a message chain.

However, there's scattered information as to what _values_ are recommendend and their semantic.

Long story short, would it be possible to include some suggestions, so to speak, in the spec?

For example:
- `ce_conversationid` MAY be set to a globally unique id, unrelated to `ce_source`, MAY NOT be a business-related value to avoid collisions, MAY be used as a log search expression in combination with `ce_source` and `ce_subject` - imagine order numbers coming from separate legacy systems which happen to be the same
- `ce_source` MAY include structured information in URI format that could be used as a log search expression
- `ce_subject` MAY include structured information in URI format that could be used as a log search expression
- `ce_generatedbysource` MAY be set in downstream messages to the `ce_source` of the upstream message
- `ce_generatedbyid` MAY be set in downstream messages to the `ce_id` of the upstream message
- `ce_correlationid` MAY be set in downstream messages to the `ce_id` of the upstream message acting as asynchronous replies 

Any suggestion would be invaluable. 
Thank you
