### ISSUE TITLE
Question: What's best practice to add data versioning?

### ISSUE THREAD

**Issue by cmenzi** [cloudevents/spec#778]
Hi

I'm went through the latest CloudEvents docs and cannot find any examples on how to do the data versioning? 

I saw the following example of EventGrid and see that there is `eventTypeVersion` in the header, but I think this based on CloudEvents V1.

* Is the `SchemaUrl` the right element to use?
* Do I need to add `CloudEventExtension`?
* Use `GetAttributes()` and just add it? (Smelly)

Or is there something, I didn't saw?

Cédric

**Comment by duglin** [comment]
Sorry for the delay - it's been transferred.

Just my 2 cents.... 

I'm not sure there is a single right answer.

I think it would be ok to keep the same ce-type value but then add/remove fields from the event - and only change is the dataschema value (if you have that) - if you're in the situation where you're only going to support exactly one version and the old one immediately goes away. I mean, adding a "v2" to your type is nice but if everyone breaks when you switch due to a mismatch on the "type" or due to the event body changing.... either way, people need to adapt to it.

Now, if you want to support multiple types at the same time (either from your event producer) or due to your subscribers getting the same type of events from multiple event producers (and some may be at v1 and others at v2), then adding a version string to your "type" feels more correct. But I'm not sure I would say it's wrong to keep the same "type" and vary the "dataschema"  attribute instead - people just need to know what to expect and where to look, via docs I guess.

**Comment by duglin** [comment]
@jskeet on the March 4th call, @jskeet agreed to write-up a PR for the primer

**Comment by jskeet** [comment]
Unlikely to be anything this week, unfortunately. I'm hoping to carve out a bit of time next week.

**Comment by duglin** [comment]
@jskeet we can close this one, right?

**Comment by jskeet** [comment]
Yup!
