### ISSUE TITLE
"source" name/explanation

### ISSUE THREAD

**Issue by clemensv** [cloudevents/spec#82]
"This describes the software instance that emits the event at runtime (i.e. the producer). It contains sub-properties (listed below)"

The description using a "i.e." seems indicative of either the property name being too ambiguous to stand, or the description needing work. 

"Software instance" is also often an incorrect term to describe a resource/source/producer, because a resource/source/producer is often a logical concept that may run multiple instances and even be made up of multiple separate implementations that all yield the same events from the same virtual context. 

Assigned to: @clemensv

**Comment by ultrasaurus** [comment]
I've been working on [cloud events concepts](https://docs.google.com/presentation/d/1xippFyX9fXqlTWUh3waZcanVMHF12z0AbZ8EK3fk3ys/edit#slide=id.g3244de5a2d_0_0).  After last weeks discussion of what we mean by `source` I've attempted to illustrate how the different attributes might be used (currently slide 11, including image below for easy reference):

![image](https://user-images.githubusercontent.com/41906/36771466-7b7d024a-1c05-11e8-9f96-0c054f0e0c71.png)

**Comment by yaronha** [comment]
@ultrasaurus @clemensv @duglin  there seem to be an overlap (same prefix) between source-type & event-type, and between namespace & source-id, IMO Cloud events "envelop" doesn't need the level of details in source-id since this is event class specific and belongs in the event body/data.  

I'm still not sure what the "namespace" stands for (whats the diff between acme.com & org.samba), and how all of this relates the the Schema field which may overlap with the event-type.

We need to keep it simple have one field for source RN and one field for Schema, all the rest of the details need to go into the event body, the source in the "envelop" needs to serve for auditing/logging and routing purposes, not for understanding the content of the event.

**Comment by duglin** [comment]
@clemensv given the current text in the spec for `source` is this issue resolved?

**Comment by duglin** [comment]
@clemensv can we close this one?

**Comment by duglin** [comment]
Agreed to close on the 5/24 call
