### ISSUE TITLE
RFC: CloudEvents in JSON:API format?

### ISSUE THREAD

**Issue by muenchhausen** [cloudevents/spec#828]
[JSON:API](https://jsonapi.org/) claims to be a „specification for building APIs in JSON“. It is very popular especially in REST APIs, because it defines JSON payload that is easy to understand. JSON:API helps to structure in a simple way e.g.
- [links](https://jsonapi.org/format/#document-links)
- [to-one relationship](https://jsonapi.org/format/#crud-updating-to-one-relationships)
- [to-many relationship](https://jsonapi.org/format/#crud-updating-to-many-relationships)
- [include related resources](https://jsonapi.org/format/#fetching-includes)
 
Why not designing both REST APIs and events consistently in JSON:API?
Why not taking from CloudEvents the envelope and from JSON:API the payload!
This would simplify the API design because you can use the same design patterns and same library functions to serialize and dezerialize both REST calls and events.
 
_There are 3 possibilities to combine JSON:API with CloudEvents - please share your thoughts on that!_
 
## Variant 1: Embedd JSON:API as CloudEvents payload
 
Using todays CloudEvents standard, you can embed JSON:API payload by nesting the `data` attribute, which is not very intuitive because two standards are combined and a nested `data/data` looks strange. Here an example of a typical business event `carOwnerChanged`:
 
```json
{
    "specversion" : "1.0",
    "type": "com.siemens.iot.vehicles.carOwnerChanged",
    "source": "https://github.com/cloudevents/example/cars",
    "id": "3056955a-f7f3-493e-b58b-5e576935d0e5",
    "time": "2021-04-19T12:00:12+00Z",
    "correlationId": "2b007f25-4cbe-4dc4-bd62-7903eddfef46",
    "data": {
        "data": {
            "id": "3056955a-f7f3-493e-b58b-5e576935d0e5",
            "type": "com.siemens.iot.vehicles.carOwnerChanged",
            "relationships": {
                "car": {
                    "data": {
                        "id": "592975a4-095f-4d43-aac6-a807ccf61918",
                        "type": "car"
                    }
                },
                "from": {
                    "data": {
                        "id": "392975a4-095f-4d43-aac6-a807ccf61917",
                        "type": "person"
                    }
                },
                "to": {
                   "data": {
                        "id": "192975a4-095f-4d43-aac6-a807ccf61914",
                        "type": "person"
                    }
                }
            }
        }
    }
}
```
 
## Variant 2: Embedd CloudEvents context attributes as JSON:API meta
 
it is easier to read and understand if CloudEvents attributes are embedded as JSON:API meta.
 
The idea is not new - the latest [KNX IoT specifications](https://schema.knx.org/AN198.pdf) does exactly that - but without official support by CloudEvents.
 
Here the same business event as toplevel JSON:API for comparison:
 
```json
"meta": {
    "envelope": {
        "type": "com.siemens.iot.vehicles.carOwnerChanged",
        "source": "https://github.com/cloudevents/example/cars",
        "id": "3056955a-f7f3-493e-b58b-5e576935d0e5",
        "time": "2021-04-19T12:00:12+00Z",
        "correlationId": "2b007f25-4cbe-4dc4-bd62-7903eddfef46"
    }
},
"data": {
    "id": "3056955a-f7f3-493e-b58b-5e576935d0e5",
    "type": "com.siemens.iot.vehicles.carOwnerChanged",
    "relationships": {
        "car": {
            "data": {
                "id": "592975a4-095f-4d43-aac6-a807ccf61918",
                "type": "car"
            }
        },
        "from": {
            "data": {
                "id": "392975a4-095f-4d43-aac6-a807ccf61917",
                "type": "person"
            }
        },
        "to": {
            "data": {
                "id": "192975a4-095f-4d43-aac6-a807ccf61914",
                "type": "person"
            }
        }
    }
}
```
 
## Variant 3: Embedd CloudEvents context attributes as JSON:API data attributes
 
to reduce redundancy for event `id` and `type`, it is also possible to leave away an explicit envelope - which might have drawbacks in event routering and schema validation.
 
```json
"data": {
    "id": "3056955a-f7f3-493e-b58b-5e576935d0e5",
    "type": "com.siemens.iot.vehicles.carOwnerChanged",
    "attributes": {
        "source": "https://github.com/cloudevents/example/cars",
        "time": "2021-04-19T12:00:12+00Z",
        "correlationId": "2b007f25-4cbe-4dc4-bd62-7903eddfef46"
    },
    "relationships": {
        "car": {
            "data": {
                "id": "592975a4-095f-4d43-aac6-a807ccf61918",
                "type": "car"
            }
        },
        "from": {
            "data": {
                "id": "392975a4-095f-4d43-aac6-a807ccf61917",
                "type": "person"
            }
        },
       "to": {
            "data": {
                "id": "192975a4-095f-4d43-aac6-a807ccf61914",
                "type": "person"
            }
        }
    }
}
```

cc @bernhard-gatzhammer

**Comment by duglin** [comment]
@muenchhausen CloudEvents doesn't really define an event format. While we do define a "structured Cloud Event", we only do that as a wrapper for the true event if someone really does want to put the CE attributes in the HTTP Body. But in many cases the event format will be defined by the event producer and the CE attributes would appear as HTTP headers - in the HTTP case. If I understand your proposal correctly, you're coming closer to defining a "common event format" and that's not something that the CE spec(s) are trying to do. A key principle of CE is that we want to be viewed as an extension to existing events/messages - which in most cases means the CE attribute would appear in the extensions of an existing message. But a key thing here is that it would be in the "message" not the "event". The original event should remain untouched by CE so that we don't interfere with existing tooling.

**Comment by bernhard-gatzhammer** [comment]
@duglin If you look at Variant 2 in the proposal above, this could be viewed as a mapping of CE attributes to JSON:API. JSON:API provides a mechanism to attach meta properties to the actual primary data, which is defined in property "data". So in that sense CE would not define how the true event looks like. We understood the mappings in CE are exactly there to allow catering to different transport "media types". The advantage would be reduced complexity when modeling HTTP and event APIs based on JSON:API.

**Comment by muenchhausen** [comment]
This RFC is more about "[Want to add a binding to a proprietary transport](https://github.com/cloudevents/spec/blob/v1.0.1/proprietary-specs.md)" or what is you opinon if this makes sense. More concrete:

Variant 1 is exactly covered by [json-format.md](https://github.com/cloudevents/spec/blob/v1.0.1/json-format.md) - but not nice.
Variant 2 and 3 would be a new spec _json-api-format.json_.

**Comment by clemensv** [comment]
We focus on interoperability in the project. While that requires supporting multiple transports and encodings, it's not helping with interoperability to accommodate everyone's or every other project's particular taste in how they want to lay out data within any given encoding. 

We chose what we felt was the simplest possible representation of metadata and data in JSON with a flat list inside an object that then also hosts the body as one of the attributes.

What you are proposing with Variants 2 and 3 are effectively variations of SOAP envelopes expressed in JSON and we've got enough late 1990s veterans here in this project remembering how that all went. If you go back into the project history here, you will find a substantial number of conversations about the pros and cons of attribute bags and we decided against them.

That leaves Variant 1, which is you leveraging CloudEvents' ability to host any arbitrary JSON content inside the "data" field, especially in structured mode. Since we accidentally use the same attribute name "data" and if JSON:API isn't allergic to extra attributes parallel to it, a CloudEvents might instantly be a valid JSON:API object as it stands, i.e. I would fold the inner "data" of JSON:API onto the "data" of CloudEvents.

```
{
    "specversion" : "1.0",
    "type": "com.siemens.iot.vehicles.carOwnerChanged",
    "source": "https://github.com/cloudevents/example/cars",
    "id": "3056955a-f7f3-493e-b58b-5e576935d0e5",
    "time": "2021-04-19T12:00:12+00Z",
    "correlationId": "2b007f25-4cbe-4dc4-bd62-7903eddfef46",
    "data": { // CloudEvent payload doubling as JSON:API object
            "id": "3056955a-f7f3-493e-b58b-5e576935d0e5",
            "type": "com.siemens.iot.vehicles.carOwnerChanged",
            "relationships": {
                "car": {
                    "data": {
                        "id": "592975a4-095f-4d43-aac6-a807ccf61918",
                        "type": "car"
                    }
                },
                "from": {
                    "data": {
                        "id": "392975a4-095f-4d43-aac6-a807ccf61917",
                        "type": "person"
                    }
                },
                "to": {
                   "data": {
                        "id": "192975a4-095f-4d43-aac6-a807ccf61914",
                        "type": "person"
                    }
                }
        }
    }
}
```
    
I don't think Variant 1 requires any changes in CloudEvents or extra spec, because it's purely a payload convention and those are not in scope.

**Comment by duglin** [comment]
We discussed this on last week's call and decided to close this. We can continue the discussion if you'd like and can reopen it if needed.
