### ISSUE TITLE
Support for using the data field in filtering

### ISSUE THREAD

**Issue by adgerrits** [cloudevents/spec#862]
It looks like the WIP subscriptions-API, including the CE Sql Expression Language text, will support filtering only through the use of context attributes and not the 'data' attribute that encapsultes payload data.

> The CloudEvents Expression Language doesn't support the handling of the data field of the CloudEvent instances, due to its polymorphic nature and complexity. We strongly encourage users that needs this functionality to use other more appropriate tools.

Support for using payload data attributes could prevent the usage of different tools, complex formatting of information in attributes like 'subject' and the development of multiple similar proprietary filter dialects that allow payload data usage (e.g. by referring to JSON-structured payload data as 'data.[attributename]' in selection criteria). It could be a producer's choice whether to allow use of the data field for filtering.

**Comment by clemensv** [comment]
The reason why most message and event brokers never touch the message body is because it drags an enormous number of dependencies into the broker and is terrible for reliability and performance:

- The broker needs to detect the payload encodings (character set and serialization format for text) and parse the payload into a structured data graph to operate on. The wire footprint of message can easily expand by several multiples in memory. The broker would have to understand a broad range of encodings to provide this feature consistently.
- Binary, schema-bound encodings would require the broker to have access to the schema driving the serializer. That will have to be stored and managed and for performant operation, that registry would need to be internal to the broker.
- The broker then needs to execute the filter expression tree against the payload. Depending on the complexity of payload and expression, that may be an enormously expensive operation both in terms of CPU and memory usage. Since users may be able to craft messages specifically to drive up resource consumption, this is also a potential DoS vector. 
- The approach is not compatible with end-to-end encryption even if the payload were parseable. 

It is possible to define a filter dialect that directly references the expression language and permits access to the data field as a proprietary extension. The consensus on today's WG call discussing the issue was that we do not want for the core spec to allow for filter access to `data` for the aforementioned reasons.

**Comment by adgerrits** [comment]
Thank you for the extensive explanation. It does pose a challenge for the context in which I work where there is a frequent need for filtering via multiple payload attributes. But as Einstein once said, "In the middle of every difficulty lies opportunity".
