### ISSUE TITLE
SDK support for batched content mode

### ISSUE THREAD

**Issue by lance** [cloudevents/spec#910]
I have a question about support for batched content mode in the SDKs. Currently, the JavaScript SDK does not support it. We have recently had an [issue](https://github.com/cloudevents/sdk-javascript/issues/440) opened about it where I asserted that it was not part of the [technical requirements](https://github.com/cloudevents/spec/blob/v1.0.1/SDK.md#technical-requirements) for an SDK. When going back to read those requirements it struck me that it's actually not very clear what is expected of an SDK. The document states:

> Supports HTTP transport renderings in both structured and binary encodings.

Which is just slightly different wording than is used in the actual HTTP protocol binding spec. The spec refers to structured, binary and batched "content mode". I may just be picking nits here, but in my opinion, the SDK guide and the HTTP transport spec should use the same terminology.

In this case, I think the SDK document should be changed to say "structured and binary content mode". But it may be that I am misunderstanding something here. It is a little odd, because batched content mode is really a specialized form of structured content mode, it seems.

In [structured mode](https://github.com/cloudevents/spec/blob/v1.0.1/http-protocol-binding.md#32-structured-content-mode), we keep "event metadata and data together in the payload, allowing simple forwarding of the same event across multiple routing hops, and across multiple protocols." Batch is no different. It's just a different content type header, and a bunch of events instead of just one.

I think that our SDK guidance is unclear on what exactly the requirement is.

**Comment by jskeet** [comment]
The whole "what is an event format" has a few wrinkles to it when you dive into details, yes.

For C#, in order to implement an event format, you can support:

- Structured mode
- Binary mode
- Batch

Structured mode and batch are slightly different because they have different method signature requirements - in JavaScript you might be able to ignore that. For the JSON event format, the batch mode delegates a lot of the implementation to the structured mode code.

The C# [CloudEventFormatter code](https://github.com/cloudevents/sdk-csharp/blob/master/src/CloudNative.CloudEvents/CloudEventFormatter.cs) may be useful to you - or not. I'm happy to chat about it on a call some time if that's helpful... and also review any suggested SDK documentation changes.

**Comment by duglin** [comment]
I think "s/encodings/content modes/g" is fine if that makes it clearer. But I think the real issue is whether "batch" is required and therefore the list should include all 3 items, or keep it at 2, right? On the call @clemensv spoke up in favor of making it required. I tend to agree, but not so much because of batch itself, as much as I'm more interested in having the broadest interop across the SDKs as possible.

Is adding support in Javascript a large ask?

**Comment by lance** [comment]
> But I think the real issue is whether "batch" is required and therefore the list should include all 3 items, or keep it at 2, right?

Basically, yes. Although I think the wording _should_ be consistent as well.

> Is adding support in Javascript a large ask?

It's all a matter of priorities these days. :) I will poke around and see if I can find someone to help out with it.

**Comment by lance** [comment]
FYI https://github.com/cloudevents/sdk-javascript/pull/448

**Comment by duglin** [comment]
@lance should we close this issue? Is there more for the group to discuss?

**Comment by pierDipi** [comment]
FYI, Java and Go SDK don't support batch content mode.

**Comment by lance** [comment]
@duglin I created a very small PR to tweak the SDK requirements wording.

**Comment by lance** [comment]
Fixed in https://github.com/cloudevents/spec/pull/915

Closing
