### ISSUE TITLE
Use of "epoch" to mean "version" in Discovery

### ISSUE THREAD

**Issue by jskeet** [cloudevents/spec#913]
The Discovery spec uses the "epoch" attribute as a form of version, and I don't currently understand the choice of term. I'd normally expect an epoch to be a sort of "reference point" from which other values are computed, e.g. timestamps being represented as "a number of seconds since the Unix epoch".

Is the Discovery use of the term epoch one which is common in other protocols?

**Comment by wenfengwang** [comment]
I first met the `epoch` is in `ZAB Protocol` and spend a lot of time understanding its meaning is that `The Term of Leader`. In `Raft Protocol`, it uses `Term` more understandable to people.  So, I also think the `version` is better than `epoch` because of the more understandable too.

**Comment by jskeet** [comment]
Proposal: `entry_version` (or `entryVersion` depending on #914).

This is mostly based on this part:

> This allows for a quick integer comparision to determine which version of this Service Entry is the latest - meaning, the one with the larger integer value.

This is not just `version` as it's not intended to relate to a version of the service itself, just its Discovery metadata. I'd be happy with `metadata_version` or similar too.

**Comment by duglin** [comment]
I'm a bit uncomfortable with the word "version" being in there because I think people will interpret it to have more meaning than what we intended. I believe the orignal usage of this field is to be able to pick the newer one when comparing two instances of the entry. And while "version" can do that, I think using a term that people might want to use for their own purposes (or confuse it with one) will be more trouble than its worth. I wonder if we could get the same semantics via something like "updatedtimestamp" and require it to include a timezone ??

**Comment by duglin** [comment]
Moved to: https://github.com/xregistry/spec/issues/9
